/**
 * Generated by tsnapi — public API snapshot of `@devframes/service-shiki`
 */
// #region Interfaces
export interface ShikiHighlightInput {
  code: string;
  lang?: string;
  themes?: ShikiThemes;
}
export interface ShikiServiceApi {
  highlight: (_: ShikiHighlightInput) => Promise<{
    html: string;
  }>;
  codeToHast: (_: ShikiHighlightInput) => Promise<ShikiHast>;
  codeToTokens: (_: ShikiHighlightInput) => Promise<ShikiTokens>;
}
export interface ShikiServiceOptions {
  themes?: ShikiThemes;
  langs?: string[];
}
export interface ShikiThemes {
  light: string;
  dark: string;
}
// #endregion

// #region Types
export type ShikiHast = Awaited<ReturnType<typeof codeToHast>>;
export type ShikiTokens = Awaited<ReturnType<typeof codeToTokens>>;
// #endregion

// #region Functions
export declare function createShikiService(_?: ShikiServiceOptions): DevframeServiceDefinition<ShikiServiceApi, ShikiServiceOptions>;
// #endregion

// #region Variables
export declare const SHIKI_DEFAULT_THEMES: ShikiThemes;
export declare const SHIKI_SERVICE_PACKAGE: string;
export declare const SHIKI_SERVICE_SCOPE: string;
// #endregion

// #region Default Export
declare function _default(_?: ShikiServiceOptions): DevframeServiceDefinition<ShikiServiceApi, ShikiServiceOptions>;
export default _default
// #endregion