/**
 * Generated by tsnapi — public API snapshot of `@devframes/json-render/core`
 */
// #region Other
export { Catalog }
export { createStateStore }
export { defineCatalog }
export { defineSchema }
export { InferActionParams }
export { InferCatalogActions }
export { InferCatalogComponents }
export { InferCatalogInput }
export { InferComponentProps }
export { InferSpec }
export { Schema }
export { SchemaBuilder }
export { SchemaDefinition }
export { SchemaOptions }
export { SchemaType }
export { Spec }
export { StateModel }
export { StateStore }
export { UIElement }
// #endregion