/**
 * Generated by tsnapi — public API snapshot of `@devframes/json-render/hub`
 */
// #region Interfaces
export interface DevframeJsonRenderDockEntry extends DevframeDockEntryBase {
  type: 'json-render';
  view: JsonRenderViewRef;
}
// #endregion

// #region Types
export type JsonRenderDockMountOptions = DockRendererMountOptions<DevframeJsonRenderDockEntry>;
export type JsonRenderDockRenderer = DockRenderer<DevframeJsonRenderDockEntry>;
// #endregion

// #region Functions
export declare function toJsonRenderDockEntry(_: JsonRenderView, _: Omit<DevframeJsonRenderDockEntry, 'type' | 'view'>): DevframeJsonRenderDockEntry;
// #endregion