/**
 * Generated by tsnapi — public API snapshot of `@devframes/json-render/hub`
 */
// #region Interfaces
export interface DevframeJsonRenderDockEntry extends DevframeDockEntryBase {
  type: 'json-render';
  view: JsonRenderViewRef;
}
export interface JsonRenderRpcContext {
  rpc: Pick<DevframeRpcClient, 'call' | 'sharedState'> & {
    connectionMeta?: Pick<ConnectionMeta, 'backend'>;
  };
}
// #endregion

// #region Types
export type JsonRenderDockMountOptions<Context = DevframeClientContext> = Omit<DockRendererMountOptions<DevframeJsonRenderDockEntry>, 'context'> & {
  context: Context;
};
export type JsonRenderDockRenderer<Context = DevframeClientContext> = (_: JsonRenderDockMountOptions<Context>) => DockRendererInstance | Promise<DockRendererInstance>;
// #endregion

// #region Functions
export declare function toJsonRenderDockEntry(_: JsonRenderView, _: Omit<DevframeJsonRenderDockEntry, 'type' | 'view'>): DevframeJsonRenderDockEntry;
// #endregion