/**
 * Generated by tsnapi — public API snapshot of `@devframes/json-render/node`
 */
// #region Interfaces
export interface CreateJsonRenderViewOptions<SpecType extends DevframeJsonRenderSpec = DevframeJsonRenderSpec> {
  id: string;
  spec: SpecType;
  schema?: StandardSchemaV1 | false;
  scope?: string;
  title?: string;
}
// #endregion

// #region Functions
export declare function createJsonRenderView<SpecType extends DevframeJsonRenderSpec = DevframeJsonRenderSpec>(_: AnyContext, _: CreateJsonRenderViewOptions<SpecType>): JsonRenderView<SpecType>;
// #endregion

// #region Variables
export declare const jsonRenderDiagnostics: Diagnostics<{
  readonly DF0038: {
    readonly why: (p: {
      id: string;
      key: string;
      issues: string;
    }) => string;
    readonly fix: "Match the element props to the base catalog's prop schema for that component. See the component reference for the expected shape.";
  };
  readonly DF0039: {
    readonly why: (p: {
      id: string;
      scope: string;
    }) => string;
    readonly fix: "Give each view a stable id unique within its scope, or dispose the previous view before recreating it.";
  };
  readonly DF0040: {
    readonly why: (p: {
      id: string;
    }) => string;
    readonly fix: "Create a fresh view with `createJsonRenderView` instead of reusing a disposed handle.";
  };
  readonly DF0041: {
    readonly why: (p: {
      id: string;
      reason: string;
    }) => string;
    readonly fix: "Specs and state travel as strict JSON, so remove functions, symbols, class instances, Map/Set, or circular references.";
  };
  readonly DF0073: {
    readonly why: (p: {
      id: string;
      issues: string;
    }) => string;
    readonly fix: "Match the authored spec to the Standard Schema passed to `createJsonRenderView`.";
  };
  readonly DF0074: {
    readonly why: (p: {
      id: string;
    }) => string;
    readonly fix: "Use a synchronous Standard Schema so initial creation and updates remain synchronous.";
  };
}, readonly [(d: Diagnostic, { method }?: {
  method?: "log" | "warn" | "error";
}) => void]>;
// #endregion

// #region Referenced (internal)
type AnyContext = DevframeNodeContext | DevframeScopedNodeContext<string>;
declare class Diagnostic extends Error {
  name: string;
  code: string;
  docs?: string;
  fix?: string;
  sources?: string[];
  get why(): string;
  constructor(_: DiagnosticInit, _?: Function);
  toJSON(): object;
}
type Diagnostics<Codes extends Record<string, DiagnosticDefinition>, Reporters extends readonly AnyDiagnosticReporter[]> = { [Code in keyof Codes]: DiagnosticHandle<InferCodeParams<Codes[Code]>, Prettify<ExtractReportersOptions<Reporters>>>; };
declare namespace StandardSchemaV1 {
  interface Props<Input = unknown, Output = Input> extends StandardTypedV1.Props<Input, Output> {
    readonly validate: (_: unknown, _?: StandardSchemaV1.Options | undefined) => Result<Output> | Promise<Result<Output>>;
  }
  type Result<Output> = SuccessResult<Output> | FailureResult;
  interface SuccessResult<Output> {
    readonly value: Output;
    readonly issues?: undefined;
  }
  interface Options {
    readonly libraryOptions?: Record<string, unknown> | undefined;
  }
  interface FailureResult {
    readonly issues: ReadonlyArray<Issue>;
  }
  interface Issue {
    readonly message: string;
    readonly path?: ReadonlyArray<PropertyKey | PathSegment> | undefined;
  }
  interface PathSegment {
    readonly key: PropertyKey;
  }
  interface Types<Input = unknown, Output = Input> extends StandardTypedV1.Types<Input, Output> {}
  type InferInput<Schema extends StandardTypedV1> = StandardTypedV1.InferInput<Schema>;
  type InferOutput<Schema extends StandardTypedV1> = StandardTypedV1.InferOutput<Schema>;
}
// #endregion