/**
 * Generated by tsnapi — public API snapshot of `@devframes/json-render/node`
 */
// #region Interfaces
export interface CreateJsonRenderViewOptions {
  id: string;
  spec: DevframeJsonRenderSpec;
  scope?: string;
}
// #endregion

// #region Functions
export declare function createJsonRenderView(_: AnyContext, _: CreateJsonRenderViewOptions): JsonRenderView;
// #endregion

// #region Variables
export declare const jsonRenderDiagnostics: import("nostics").Diagnostics<{
  readonly DF0038: {
    readonly why: (p: {
      id: string;
      key: string;
      issues: string;
    }) => string;
    readonly fix: "Match the element props to the base catalog's prop schema for that component. See the component reference for the expected shape.";
  };
  readonly DF0039: {
    readonly why: (p: {
      id: string;
      scope: string;
    }) => string;
    readonly fix: "Give each view a stable id unique within its scope, or dispose the previous view before recreating it.";
  };
  readonly DF0040: {
    readonly why: (p: {
      id: string;
    }) => string;
    readonly fix: "Create a fresh view with `createJsonRenderView` instead of reusing a disposed handle.";
  };
  readonly DF0041: {
    readonly why: (p: {
      id: string;
      reason: string;
    }) => string;
    readonly fix: "Specs and state travel as strict JSON — remove functions, symbols, class instances, Map/Set, or circular references.";
  };
}, readonly [typeof jsonRenderReporter]>;
// #endregion