/**
 * Generated by tsnapi — public API snapshot of `@devframes/json-render/view`
 */
// #region Interfaces
export interface CreateJsonRenderViewOptions<SpecType extends DevframeJsonRenderSpec = DevframeJsonRenderSpec> {
  id: string;
  spec: SpecType;
  schema?: StandardSchemaV1 | false;
  scope?: string;
  title?: string;
}
export interface JsonRenderScopedViewContext {
  base: JsonRenderViewContext;
  namespace: string;
}
export interface JsonRenderViewContext {
  rpc: {
    sharedState: RpcSharedStateHost;
  };
}
// #endregion

// #region Functions
export declare function createJsonRenderView<SpecType extends DevframeJsonRenderSpec = DevframeJsonRenderSpec>(_: AnyContext, _: CreateJsonRenderViewOptions<SpecType>): JsonRenderView<SpecType>;
// #endregion

// #region Referenced (internal)
type AnyContext = JsonRenderViewContext | JsonRenderScopedViewContext;
// #endregion