/**
 * Generated by tsnapi — public API snapshot of `@devframes/hub-ui-onboard`
 */
// #region Interfaces
export interface CreateOnboardingOptions {
  packages: string[];
  base?: string;
  cwd?: string;
  stateDir?: string;
  dev?: boolean;
  branding?: OnboardingBranding;
  messages?: Partial<OnboardingMessages>;
  onInstalled?: () => void | OnboardingHandler | Promise<void | OnboardingHandler>;
}
export interface Onboarding {
  handler: OnboardingHandler;
  nodeMiddleware: (_: import('node:http').IncomingMessage, _: import('node:http').ServerResponse, _?: (_?: unknown) => void) => void;
  disabled: boolean;
  scriptSrc: string;
}
export interface OnboardingBranding {
  productName?: string;
  logo?: OnboardingLogo;
  primaryColor?: string;
}
export interface OnboardingMessages {
  title: string;
  description: string;
  install: string;
  disable: string;
  installing: string;
  restart: string;
  retry: string;
}
export interface OnboardingStatus {
  state: OnboardingState;
  command: string;
  branding: OnboardingBranding;
  messages: OnboardingMessages;
  error?: {
    code: string;
    message: string;
  };
}
// #endregion

// #region Types
export type OnboardingHandler = (_: Request) => Response | Promise<Response>;
export type OnboardingLogo = string | {
  light: string;
  dark?: string;
};
export type OnboardingState = 'idle' | 'installing' | 'installed' | 'ready' | 'error' | 'disabled';
// #endregion

// #region Functions
export declare function createOnboarding(_: CreateOnboardingOptions): Onboarding;
// #endregion