/**
 * Generated by tsnapi — public API snapshot of `@devframes/json-render-ui/renderer`
 */
// #region Default Export
declare const _default: JsonRenderDockRenderer<JsonRenderRpcContext>;
export default _default
// #endregion