/**
 * Generated by tsnapi — public API snapshot of `@devframes/json-render-ui/spa`
 */
// #region Functions
export declare function createJsonRenderDevframe(_: DevframeDefinition): DevframeDefinition;
// #endregion

// #region Variables
export declare const jsonRenderSpaDir: string;
// #endregion