/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/crypto-token`
 */
// #region Functions
export declare function randomDigits(_: number): string;
export declare function randomToken(_?: number): string;
export declare function timingSafeEqual(_: string, _: string): boolean;
// #endregion