/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/debounce`
 */
// #region Interfaces
export interface DebounceOptions {
  readonly leading?: boolean;
  readonly trailing?: boolean;
}
// #endregion

// #region Types
export type DebouncedReturn<ArgumentsT extends unknown[], ReturnT> = ((..._: ArgumentsT) => Promise<ReturnT>) & {
  cancel: () => void;
  flush: () => Promise<ReturnT> | undefined;
  isPending: () => boolean;
};
// #endregion

// #region Functions
export declare function debounce<ArgumentsT extends unknown[], ReturnT>(_: (..._: ArgumentsT) => PromiseLike<ReturnT> | ReturnT, _?: number, _?: DebounceOptions): DebouncedReturn<ArgumentsT, ReturnT>;
// #endregion