/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/get-port`
 */
// #region Interfaces
export interface GetPortOptions {
  name: string;
  random: boolean;
  port: number;
  ports: number[];
  portRange: [fromInclusive: number, toInclusive: number];
  alternativePortRange: [fromInclusive: number, toInclusive: number];
  host: string;
  verbose?: boolean;
  public?: boolean;
}
// #endregion

// #region Types
export type GetPortInput = Partial<GetPortOptions> | number | string;
// #endregion

// #region Functions
export declare function getPort(_?: GetPortInput): Promise<PortNumber>;
// #endregion

// #region Referenced (internal)
type PortNumber = number;
// #endregion