/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/nostics`
 */
// #region Other
export { ansiFormatter }
export { AnyDiagnosticReporter }
export { ConsoleMethod }
export { ConsoleReporterOptions }
export { createConsoleReporter }
export { defineDiagnostics }
export { defineProdDiagnostics }
export { DevframeDefineDiagnosticsOptions }
export { Diagnostic }
export { DiagnosticCallParams }
export { DiagnosticDefinition }
export { DiagnosticHandle }
export { DiagnosticInit }
export { DiagnosticReporter }
export { Diagnostics }
export { formatDiagnostic }
// #endregion