/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/origin`
 */
// #region Other
export { isAllowedOrigin }
export { isLoopbackHostname }
export { validateOriginCandidate }
// #endregion