/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/remote-assets`
 */
// #region Functions
export declare function resolveStaticAssetsSource(_: StaticAssetsSource, _: string, _?: string | null): string | RemoteAssetsStore;
// #endregion