/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/remote-assets`
 */
// #region Interfaces
export interface CreateRemoteAssetsStoreOptions {
  cacheDir: string;
}
export interface ResolveStaticAssetsSourceOptions {
  cacheRoot: string;
}
// #endregion

// #region Functions
export declare function createRemoteAssetsStore(_: RemoteAssets, _: CreateRemoteAssetsStoreOptions): RemoteAssetsStore;
export declare function remoteAssetsCacheDir(_: string, _: RemoteAssets): string;
export declare function remoteAssetsCacheRoot(_: string): string;
export declare function renderRemoteAssetsErrorPage(_: {
  package: string;
  version: string;
  reason: string;
}): string;
export declare function resolveInstalledRemoteAssets(_: RemoteAssets): string | undefined;
export declare function resolveStaticAssetsSource(_: StaticAssetsSource, _: ResolveStaticAssetsSourceOptions): string | RemoteAssetsStore;
// #endregion