/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/scope`
 */
// #region Functions
export declare function isQualifiedName(_: string): boolean;
export declare function qualifyName(_: string, _: string): string;
// #endregion