/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/serve-static`
 */
// #region Interfaces
export interface ServeStaticOptions {
  indexNames?: string[];
  single?: boolean;
}
// #endregion

// #region Functions
export declare function mountStaticHandler(_: H3, _: string, _: string, _?: ServeStaticOptions): void;
export declare function serveStaticHandler(_: string, _?: ServeStaticOptions): EventHandler;
export declare function serveStaticNodeMiddleware(_: string, _?: ServeStaticOptions): (_: IncomingMessage, _: ServerResponse, _?: (_?: Error) => void) => void;
// #endregion