/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/simple-schema`
 */
// #region Interfaces
export interface SimpleSchema<Input, Output = Input> extends StandardSchemaV1<Input, Output> {
  readonly type: string;
  readonly wrapped?: StandardSchemaV1;
  readonly description?: string;
}
// #endregion

// #region Functions
export declare function array<T extends StandardSchemaV1>(_: T): SimpleSchema<StandardSchemaV1.InferInput<T>[], StandardSchemaV1.InferOutput<T>[]>;
export declare function boolean(): SimpleSchema<boolean>;
export declare function describe<T extends SimpleSchema<any, any>>(_: T, _: string): T;
export declare function literal<const T extends string | number | boolean>(_: T): SimpleSchema<T>;
export declare function nullable<T extends StandardSchemaV1>(_: T): SimpleSchema<StandardSchemaV1.InferInput<T> | null, StandardSchemaV1.InferOutput<T> | null>;
export declare function nullType(): SimpleSchema<null>;
export declare function number(): SimpleSchema<number>;
export declare function object<T extends Record<string, StandardSchemaV1>>(_: T): SimpleSchema<InferObject<T, 'input'>, InferObject<T, 'output'>>;
export declare function optional<T extends StandardSchemaV1>(_: T): SimpleSchema<StandardSchemaV1.InferInput<T> | undefined, StandardSchemaV1.InferOutput<T> | undefined>;
export declare function picklist<const T extends readonly (string | number | boolean)[]>(_: T): SimpleSchema<T[number]>;
export declare function record<V extends StandardSchemaV1>(_: StandardSchemaV1, _: V): SimpleSchema<Record<string, StandardSchemaV1.InferInput<V>>, Record<string, StandardSchemaV1.InferOutput<V>>>;
export declare function string(): SimpleSchema<string>;
export declare function union<const T extends readonly StandardSchemaV1[]>(_: T): SimpleSchema<StandardSchemaV1.InferInput<T[number]>, StandardSchemaV1.InferOutput<T[number]>>;
export declare function voidType(): SimpleSchema<void>;
// #endregion

// #region Variables
export declare const s: {
  readonly string: typeof string;
  readonly number: typeof number;
  readonly boolean: typeof boolean;
  readonly void: typeof voidType;
  readonly null: typeof nullType;
  readonly literal: typeof literal;
  readonly picklist: typeof picklist;
  readonly union: typeof union;
  readonly record: typeof record;
  readonly array: typeof array;
  readonly object: typeof object;
  readonly optional: typeof optional;
  readonly nullable: typeof nullable;
  readonly describe: typeof describe;
};
// #endregion