/**
 * Generated by tsnapi — public API snapshot of `devframe/utils/url`
 */
// #region Functions
export declare function cleanDoubleSlashes(_: string): string;
export declare function joinURL(_: string, ..._: string[]): string;
export declare function withBase(_: string, _: string): string;
export declare function withLeadingSlash(_: string): string;
export declare function withoutLeadingSlash(_: string): string;
export declare function withoutTrailingSlash(_: string): string;
export declare function withProtocol(_: string, _: string): string;
export declare function withTrailingSlash(_: string): string;
// #endregion