/**
 * Generated by tsnapi — public API snapshot of `@devframes/nuxt`
 */
// #region Re-exports
export { default } from './module.mjs';
export { type ModuleOptions, type DevframeNuxtModuleOptions } from './module.mjs';
// #endregion