/**
 * Generated by tsnapi — public API snapshot of `devframe/rpc/dump`
 */
// #region Interfaces
export interface StaticRpcDumpCollection {
  manifest: StaticRpcDumpManifest;
  files: Record<string, StaticRpcDumpFile>;
}
export interface StaticRpcDumpFile {
  serialization: StaticRpcDumpSerialization;
  fnName: string;
  data: unknown;
}
export interface StaticRpcDumpManifestQueryEntry {
  type: 'query';
  records: Record<string, string>;
  fallback?: string;
  serialization?: StaticRpcDumpSerialization;
}
export interface StaticRpcDumpManifestStaticEntry {
  type: 'static';
  path: string;
  serialization?: StaticRpcDumpSerialization;
}
export interface WriteStaticRpcDumpOptions {
  pretty?: boolean;
}
// #endregion

// #region Types
export type StaticRpcDumpManifest = Record<string, StaticRpcDumpManifestValue>;
export type StaticRpcDumpManifestValue = StaticRpcDumpManifestStaticEntry | StaticRpcDumpManifestQueryEntry | any;
export type StaticRpcDumpSerialization = 'json' | 'structured-clone';
// #endregion

// #region Functions
export declare function collectStaticRpcDump(_: Iterable<RpcFunctionDefinitionAny>, _: any): Promise<StaticRpcDumpCollection>;
export declare function createClientFromDump<T extends Record<string, any>>(_: RpcDumpStore<T>, _?: RpcDumpClientOptions): BirpcReturn<T>;
export declare function dumpFunctions<T extends readonly RpcFunctionDefinitionAny[]>(_: T, _?: any, _?: RpcDumpCollectionOptions): Promise<RpcDumpStore<RpcDefinitionsToFunctions<T>>>;
export declare function getDefinitionsWithDumps<T extends readonly RpcFunctionDefinitionAny[]>(_: T): RpcFunctionDefinitionAny[];
export declare function reviveDumpError(_: RpcDumpRecordError): Error;
export declare function serializeDumpError(_: unknown): RpcDumpRecordError;
export declare function writeStaticRpcDump(_: StaticRpcDumpCollection, _: string, _?: WriteStaticRpcDumpOptions): Promise<void>;
// #endregion