/**
 * Generated by tsnapi — public API snapshot of `devframe/rpc/dump`
 */
// #region Other
export { collectStaticRpcDump }
export { createClientFromDump }
export { dumpFunctions }
export { getDefinitionsWithDumps }
export { reviveDumpError }
export { serializeDumpError }
export { StaticRpcDumpCollection }
export { StaticRpcDumpFile }
export { StaticRpcDumpManifest }
export { StaticRpcDumpManifestQueryEntry }
export { StaticRpcDumpManifestStaticEntry }
export { StaticRpcDumpManifestValue }
export { StaticRpcDumpSerialization }
// #endregion