/**
 * Generated by tsnapi — public API snapshot of `devframe/rpc/shared-state`
 */
// #region Functions
export declare function createRpcSharedStateClientHost<Context>(_: Pick<DevframeRpcClient, 'call' | 'callEvent' | 'events' | 'isTrusted'> & {
  client: Pick<RpcFunctionsCollector<DevframeRpcClientFunctions, Context>, 'register'>;
  connectionMeta: Pick<ConnectionMeta, 'backend'>;
}): RpcSharedStateHost;
export declare function createRpcSharedStateServerHost<Context>(_: Pick<RpcFunctionsCollector<DevframeRpcServerFunctions, Context>, 'register'> & Pick<RpcFunctionsHost, 'broadcast'>): RpcSharedStateHost;
// #endregion