/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-og/client`
 */
// #region Functions
export declare function connectOg(_?: DevframeRpcClientOptions): Promise<import("devframe/client").DevframeRpcClient>;
// #endregion

// #region Other
export { DevframeConnectionStatus }
export { DevframeRpcClient }
export { OgHeadTag }
export { OgHeadTagName }
export { OgResolveInput }
export { OgSnapshot }
// #endregion