/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-og`
 */
// #region Interfaces
export interface OgDevframeOptions {
  id?: string;
  name?: string;
  icon?: string;
  basePath?: string;
  port?: number;
  auth?: boolean;
  defaultUrl?: string;
  fetch?: OgFetch;
}
export interface OgHeadTag {
  tag: OgHeadTagName;
  name: string;
  value: string;
}
export interface OgResolveInput {
  url?: string;
}
export interface OgSnapshot {
  requestedUrl: string;
  url: string;
  status: number;
  fetchedAt: number;
  tags: OgHeadTag[];
}
// #endregion

// #region Types
export type OgFetch = (_: string, _: RequestInit) => Promise<Response>;
export type OgHeadTagName = 'html' | 'link' | 'meta' | 'title';
// #endregion

// #region Functions
export declare function createOgDevframe(_?: OgDevframeOptions): DevframeDefinition;
// #endregion

// #region Default Export
declare const _default: DevframeDefinition;
export default _default
// #endregion