/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-og/rpc`
 */
// #region Variables
export declare const serverFunctions: readonly [{
  name: "devframes:plugin:og:resolve-metadata";
  type?: "query" | undefined;
  cacheable?: boolean;
  args: readonly [import("devframe/utils/simple-schema").SimpleSchema<{
    url?: string | undefined;
  }, {
    url?: string | undefined;
  }>];
  returns: import("devframe/utils/simple-schema").SimpleSchema<{
    requestedUrl: string;
    url: string;
    status: number;
    fetchedAt: number;
    tags: {
      tag: "html" | "link" | "meta" | "title";
      name: string;
      value: string;
    }[];
  }, {
    requestedUrl: string;
    url: string;
    status: number;
    fetchedAt: number;
    tags: {
      tag: "html" | "link" | "meta" | "title";
      name: string;
      value: string;
    }[];
  }>;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    url?: string | undefined;
  }], {
    requestedUrl: string;
    url: string;
    status: number;
    fetchedAt: number;
    tags: {
      tag: "html" | "link" | "meta" | "title";
      name: string;
      value: string;
    }[];
  }>>) | undefined;
  handler?: ((args_0: {
    url?: string | undefined;
  }) => {
    requestedUrl: string;
    url: string;
    status: number;
    fetchedAt: number;
    tags: {
      tag: "html" | "link" | "meta" | "title";
      name: string;
      value: string;
    }[];
  }) | undefined;
  dump?: import("devframe/rpc").RpcDump<[{
    url?: string | undefined;
  }], {
    requestedUrl: string;
    url: string;
    status: number;
    fetchedAt: number;
    tags: {
      tag: "html" | "link" | "meta" | "title";
      name: string;
      value: string;
    }[];
  }, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    url?: string | undefined;
  }], {
    requestedUrl: string;
    url: string;
    status: number;
    fetchedAt: number;
    tags: {
      tag: "html" | "link" | "meta" | "title";
      name: string;
      value: string;
    }[];
  }>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    url?: string | undefined;
  }], {
    requestedUrl: string;
    url: string;
    status: number;
    fetchedAt: number;
    tags: {
      tag: "html" | "link" | "meta" | "title";
      name: string;
      value: string;
    }[];
  }>> | undefined;
}];
// #endregion

// #region Other
export { createResolveMetadataRpc }
export { resolveMetadata }
export { ResolveMetadataOptions }
// #endregion