/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-og/rpc`
 */
// #region Variables
export declare const serverFunctions: readonly [import("devframe/rpc").RpcFunctionDefinitionWithSchemas<"devframes:plugin:og:resolve-metadata", "query", readonly [import("devframe/utils/simple-schema").SimpleSchema<{
  url?: string | undefined;
}, {
  url?: string | undefined;
}>], import("devframe/utils/simple-schema").SimpleSchema<{
  requestedUrl: string;
  url: string;
  status: number;
  fetchedAt: number;
  tags: {
    tag: "html" | "link" | "meta" | "title";
    name: string;
    value: string;
  }[];
}, {
  requestedUrl: string;
  url: string;
  status: number;
  fetchedAt: number;
  tags: {
    tag: "html" | "link" | "meta" | "title";
    name: string;
    value: string;
  }[];
}>, import("devframe").DevframeNodeContext>];
// #endregion

// #region Other
export { createResolveMetadataRpc }
export { resolveMetadata }
export { ResolveMetadataOptions }
// #endregion