/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-og/rpc`
 */
// #region Variables
export declare const serverFunctions: readonly [{
  name: "devframes:plugin:og:resolve-metadata";
  type?: "query" | undefined;
  cacheable?: boolean;
  args: readonly [import("valibot").ObjectSchema<{
    readonly url: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
  }, undefined>];
  returns: import("valibot").ObjectSchema<{
    readonly requestedUrl: import("valibot").StringSchema<undefined>;
    readonly url: import("valibot").StringSchema<undefined>;
    readonly status: import("valibot").NumberSchema<undefined>;
    readonly fetchedAt: import("valibot").NumberSchema<undefined>;
    readonly tags: import("valibot").ArraySchema<import("valibot").ObjectSchema<{
      readonly tag: import("valibot").PicklistSchema<["html", "link", "meta", "title"], undefined>;
      readonly name: import("valibot").StringSchema<undefined>;
      readonly value: import("valibot").StringSchema<undefined>;
    }, undefined>, undefined>;
  }, undefined>;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    url?: string | undefined;
  }], {
    requestedUrl: string;
    url: string;
    status: number;
    fetchedAt: number;
    tags: {
      tag: "html" | "link" | "meta" | "title";
      name: string;
      value: string;
    }[];
  }>>) | undefined;
  handler?: ((args_0: {
    url?: string | undefined;
  }) => {
    requestedUrl: string;
    url: string;
    status: number;
    fetchedAt: number;
    tags: {
      tag: "html" | "link" | "meta" | "title";
      name: string;
      value: string;
    }[];
  }) | undefined;
  dump?: import("devframe/rpc").RpcDump<[{
    url?: string | undefined;
  }], {
    requestedUrl: string;
    url: string;
    status: number;
    fetchedAt: number;
    tags: {
      tag: "html" | "link" | "meta" | "title";
      name: string;
      value: string;
    }[];
  }, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    url?: string | undefined;
  }], {
    requestedUrl: string;
    url: string;
    status: number;
    fetchedAt: number;
    tags: {
      tag: "html" | "link" | "meta" | "title";
      name: string;
      value: string;
    }[];
  }>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    url?: string | undefined;
  }], {
    requestedUrl: string;
    url: string;
    status: number;
    fetchedAt: number;
    tags: {
      tag: "html" | "link" | "meta" | "title";
      name: string;
      value: string;
    }[];
  }>> | undefined;
}];
// #endregion

// #region Other
export { createResolveMetadataRpc }
export { resolveMetadata }
export { ResolveMetadataOptions }
// #endregion