/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-og/vite`
 */
// #region Interfaces
export interface OgVitePluginOptions extends ViteDevBridgeOptions {
  auth?: boolean;
}
// #endregion

// #region Functions
export declare function ogVitePlugin(_?: OgVitePluginOptions): DevframeVitePlugin;
// #endregion

// #region Other
export { ViteDevBridgeOptions }
// #endregion