/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-messages/client`
 */
// #region Interfaces
export interface MessagesHandle {
  rpc: DevframeRpcClient;
  dispose: () => void;
}
export interface MessagesState {
  entries: DevframeMessageEntry$1[];
}
export interface MountMessagesOptions {
  rpc?: DevframeRpcClient;
}
// #endregion

// #region Functions
export declare function connectMessages(_?: DevframeRpcClientOptions): Promise<DevframeRpcClient>;
export declare function mountMessages(_: HTMLElement, _?: MountMessagesOptions): Promise<MessagesHandle>;
export declare function useMessages(_: DevframeRpcClient$1): Reactive<MessagesState>;
// #endregion

// #region Other
export { DevframeMessageEntry }
export { DevframeMessageEntryFrom }
export { DevframeMessageEntryInput }
export { DevframeMessageLevel }
export { DevframeMessagesListDelta }
export { DevframeRpcClient }
export { MESSAGES_UPDATED_EVENT }
// #endregion