/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-messages/constants`
 */
// #region Variables
export declare const DEFAULT_PORT: number;
export declare const MESSAGES_UPDATED_EVENT: string;
export declare const PLUGIN_ID: string;
// #endregion