/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-messages`
 */
// #region Interfaces
export interface MessagesDevframeOptions {
  id?: string;
  name?: string;
  icon?: string;
  basePath?: string;
  port?: number;
  auth?: boolean;
}
// #endregion

// #region Functions
export declare function createMessagesDevframe(_?: MessagesDevframeOptions): DevframeDefinition;
// #endregion

// #region Default Export
declare const _default: DevframeDefinition;
export default _default
// #endregion

// #region Other
export { DEFAULT_PORT }
export { DevframeMessageEntry }
export { DevframeMessageEntryFrom }
export { DevframeMessageEntryInput }
export { DevframeMessageLevel }
export { DevframeMessagesListDelta }
export { MESSAGES_UPDATED_EVENT }
export { PLUGIN_ID }
// #endregion