/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-messages/node`
 */
// #region Functions
export declare function setupMessages(_: DevframeNodeContext): void;
// #endregion

// #region Other
export { serverFunctions }
// #endregion