/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-messages/rpc`
 */
// #region Variables
export declare const serverFunctions: readonly [{
  name: "devframes:plugin:messages:list";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[since?: number | null | undefined], Promise<import("@devframes/hub/types").DevframeMessagesListDelta>>>) | undefined;
  handler?: ((since?: number | null | undefined) => Promise<import("@devframes/hub/types").DevframeMessagesListDelta>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[since?: number | null | undefined], Promise<import("@devframes/hub/types").DevframeMessagesListDelta>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[since?: number | null | undefined], Promise<import("@devframes/hub/types").DevframeMessagesListDelta>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[since?: number | null | undefined], Promise<import("@devframes/hub/types").DevframeMessagesListDelta>>> | undefined;
}, {
  name: "devframes:plugin:messages:add";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[input: import("@devframes/hub/types").DevframeMessageEntryInput], Promise<import("@devframes/hub/types").DevframeMessageEntry | null>>>) | undefined;
  handler?: ((input: import("@devframes/hub/types").DevframeMessageEntryInput) => Promise<import("@devframes/hub/types").DevframeMessageEntry | null>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[input: import("@devframes/hub/types").DevframeMessageEntryInput], Promise<import("@devframes/hub/types").DevframeMessageEntry | null>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[input: import("@devframes/hub/types").DevframeMessageEntryInput], Promise<import("@devframes/hub/types").DevframeMessageEntry | null>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[input: import("@devframes/hub/types").DevframeMessageEntryInput], Promise<import("@devframes/hub/types").DevframeMessageEntry | null>>> | undefined;
}, {
  name: "devframes:plugin:messages:update";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[id: string, patch: Partial<import("@devframes/hub/types").DevframeMessageEntryInput>], Promise<import("@devframes/hub/types").DevframeMessageEntry | null>>>) | undefined;
  handler?: ((id: string, patch: Partial<import("@devframes/hub/types").DevframeMessageEntryInput>) => Promise<import("@devframes/hub/types").DevframeMessageEntry | null>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[id: string, patch: Partial<import("@devframes/hub/types").DevframeMessageEntryInput>], Promise<import("@devframes/hub/types").DevframeMessageEntry | null>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[id: string, patch: Partial<import("@devframes/hub/types").DevframeMessageEntryInput>], Promise<import("@devframes/hub/types").DevframeMessageEntry | null>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[id: string, patch: Partial<import("@devframes/hub/types").DevframeMessageEntryInput>], Promise<import("@devframes/hub/types").DevframeMessageEntry | null>>> | undefined;
}, {
  name: "devframes:plugin:messages:remove";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[id: string], Promise<void>>>) | undefined;
  handler?: ((id: string) => Promise<void>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[id: string], Promise<void>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[id: string], Promise<void>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[id: string], Promise<void>>> | undefined;
}, {
  name: "devframes:plugin:messages:clear";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], Promise<void>>>) | undefined;
  handler?: (() => Promise<void>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[], Promise<void>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], Promise<void>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], Promise<void>>> | undefined;
}];
// #endregion