/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-messages/types`
 */
// #region Other
export { DevframeMessageAction }
export { DevframeMessageActivateAction }
export { DevframeMessageEntry }
export { DevframeMessageEntryFrom }
export { DevframeMessageEntryInput }
export { DevframeMessageLevel }
export { DevframeMessagesListDelta }
// #endregion