/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-messages/vite`
 */
// #region Functions
export declare function messagesVitePlugin(_?: ViteDevBridgeOptions): DevframeVitePlugin;
// #endregion

// #region Other
export { ViteDevBridgeOptions }
// #endregion