import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { createGenerator } from 'unocss'
import { presetDevframe, shortcuts } from '../src/preset'

/**
 * Emit the design package's shipped CSS:
 *
 * - `dist/theme.css` — the `--df-*` token values + base layer, verbatim.
 * - `dist/style.css` — a standalone stylesheet (UnoCSS preflights + every
 *   `df-*` component class + the tokens) for consumers that don't run UnoCSS
 *   themselves but still want the shared component vocabulary.
 */

const root = fileURLToPath(new URL('..', import.meta.url))
const distDir = resolve(root, 'dist')

async function main(): Promise<void> {
  await mkdir(distDir, { recursive: true })

  const theme = await readFile(resolve(root, 'src/theme.css'), 'utf8')
  await writeFile(resolve(distDir, 'theme.css'), theme)

  // Materialize every named `df-*` shortcut (and a few palette tags) so the
  // standalone stylesheet carries the full shared component vocabulary.
  const names = new Set<string>()
  for (const entry of shortcuts) {
    if (Array.isArray(entry))
      continue
    for (const key of Object.keys(entry))
      names.add(key)
  }
  for (const color of ['blue', 'amber', 'green', 'red', 'sky', 'violet', 'rose'])
    names.add(`df-tag-${color}`)

  const generator = await createGenerator({ presets: [presetDevframe()] })
  const { css } = await generator.generate(names, { preflights: true })

  const banner = '/* @internal/design — prebuilt stylesheet. Generated by scripts/build-css.ts; do not edit. */\n'
  await writeFile(resolve(distDir, 'style.css'), `${banner}${css}\n${theme}`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
