/**
 * Generated by tsnapi — public API snapshot of `@devframes/service-open`
 */
// #region Interfaces
export interface OpenInEditorInput {
  path: string;
  line?: number;
  column?: number;
  editor?: KnownEditor;
}
export interface OpenServiceApi {
  openInEditor: (_: OpenInEditorInput) => Promise<void>;
  openInFinder: (_: {
    path: string;
  }) => Promise<void>;
}
export interface OpenServiceOptions {
  editor?: KnownEditor;
  roots?: string[];
}
// #endregion

// #region Functions
export declare function createOpenService(_?: OpenServiceOptions): DevframeServiceDefinition<OpenServiceApi, OpenServiceOptions>;
// #endregion

// #region Variables
export declare const OPEN_SERVICE_PACKAGE: string;
export declare const OPEN_SERVICE_SCOPE: string;
// #endregion

// #region Default Export
declare function _default(_?: OpenServiceOptions): DevframeServiceDefinition<OpenServiceApi, OpenServiceOptions>;
export default _default
// #endregion