/**
 * Generated by tsnapi — public API snapshot of `@devframes/vite/dev-spa`
 */
// #region Interfaces
export interface DevframeViteBridgeOptions {
  base?: string;
  port?: number;
  host?: string;
  flags?: Record<string, unknown>;
  auth?: boolean | DevframeAuthHandler;
  mcp?: boolean | McpRouteOptions;
}
export interface DevframeViteDevServerLike {
  middlewares: {
    use: ((_: string, _: (_: IncomingMessage, _: ServerResponse, _?: (_?: unknown) => void) => void) => void) & ((_: (_: IncomingMessage, _: ServerResponse, _?: (_?: unknown) => void) => void) => void);
  };
  httpServer?: {
    once: (_: 'close', _: () => void) => unknown;
  } | null;
}
export interface DevframeViteOptions extends DevframeViteBridgeOptions {
  bridge?: boolean;
}
export interface DevframeVitePluginOptions {
  base?: string;
}
// #endregion

// #region Types
export type DevframeVitePlugin = Plugin;
// #endregion

// #region Functions
export declare function devframeVite(_: DevframeDefinition, _?: DevframeViteOptions): DevframeVitePlugin;
export declare function devframeViteBridge(_: DevframeDefinition, _?: DevframeViteBridgeOptions): DevframeVitePlugin;
export declare function devframeVitePlugin(_: DevframeDefinition, _?: DevframeVitePluginOptions): DevframeVitePlugin;
// #endregion