/**
 * Generated by tsnapi — public API snapshot of `@devframes/vite/hub`
 */
// #region Interfaces
export interface ViteDevframeHubOptions {
  base?: string;
  port?: number;
  host?: string;
  devframes?: InitHubOptions['devframes'];
  clientScripts?: Record<string, ClientScriptEntry>;
  clientModuleResolution?: string | false;
  renderers?: readonly DockRendererRegistration[];
  rpcDeclarations?: InitHubOptions['rpcDeclarations'];
  configure?: (_: DevframeHubContext) => void | Promise<void>;
  ui?: DevframeHubUi | false;
  auth?: InitHubOptions['auth'];
  mcp?: InitHubOptions['mcp'];
  register?: InitHubOptions['register'];
  origin?: InitHubOptions['origin'];
  cwd?: string;
  getStorageDir?: InitHubOptions['getStorageDir'];
  name?: string;
  version?: string;
  quiet?: boolean;
}
// #endregion

// #region Functions
export declare function viteDevframeHub(_?: ViteDevframeHubOptions): Plugin;
// #endregion

// #region Variables
export declare const VITE_CLIENT_MODULE_RESOLUTION: string;
// #endregion