/**
 * Generated by tsnapi — public API snapshot of `@devframes/hub-ui`
 */
// #region Interfaces
export interface CreateUiOptions {
  viewer?: boolean;
  embedded?: boolean;
  branding?: DevframeBranding;
}
export interface DevframeBranding {
  productName?: string;
  logo?: BrandingLogo;
  wordmark?: BrandingLogo;
  primaryColor?: string;
  tagline?: string;
  favicon?: string;
  windowTitle?: string;
}
// #endregion

// #region Functions
export declare function createUi(_?: CreateUiOptions): DevframeHubUi;
// #endregion