/**
 * Generated by tsnapi — public API snapshot of `@devframes/hub-ui`
 */
// #region Interfaces
export interface CreateUiOptions {
  viewer?: boolean;
  embedded?: boolean;
  branding?: DevframeBranding;
  embeddedVisibility?: EmbeddedVisibility;
  dockPreferences?: DevframeDockPreferences;
  locale?: HubUiLocale;
}
export interface DevframeBranding {
  productName?: string;
  logo?: BrandingLogo;
  wordmark?: BrandingLogo;
  primaryColor?: string;
  background?: ViewerBackground;
  tagline?: string;
  favicon?: string;
  windowTitle?: string;
}
export interface DevframeDockPreferences {
  categoryOrder?: Record<string, number>;
  maxVisibleItems?: number;
  defaultMode?: 'float' | 'edge';
  defaultPosition?: 'left' | 'right' | 'top' | 'bottom';
}
// #endregion

// #region Types
export type ColorSchemeValue = string | {
  light: string;
  dark: string;
};
export type EmbeddedVisibility = 'normal' | 'passive' | 'hidden';
export type HubUiLocale = keyof typeof HUB_UI_LOCALES;
export type ViewerBackground = ColorSchemeValue | {
  standalone: ColorSchemeValue;
  iframe?: ColorSchemeValue;
};
// #endregion

// #region Functions
export declare function createUi(_?: CreateUiOptions): DevframeHubUi;
// #endregion

// #region Variables
export declare const HUB_UI_LOCALES: {
  readonly en: "English";
  readonly 'zh-CN': "简体中文";
  readonly 'zh-TW': "繁體中文";
  readonly ja: "日本語";
  readonly ko: "한국어";
  readonly es: "Español";
  readonly fr: "Français";
  readonly de: "Deutsch";
  readonly 'pt-BR': "Português (Brasil)";
  readonly ru: "Русский";
};
// #endregion

// #region Referenced (internal)
type BrandingLogo = string | {
  light: string;
  dark: string;
};
// #endregion