/**
 * Generated by tsnapi — public API snapshot of `@devframes/hub-ui`
 */
// #region Interfaces
export interface CreateUiOptions {
  viewer?: boolean;
  embedded?: boolean;
  branding?: DevframeBranding;
  embeddedVisibility?: EmbeddedVisibility;
  dockPreferences?: DevframeDockPreferences;
}
export interface DevframeBranding {
  productName?: string;
  logo?: BrandingLogo;
  wordmark?: BrandingLogo;
  primaryColor?: string;
  background?: 'default' | 'transparent';
  tagline?: string;
  favicon?: string;
  windowTitle?: string;
}
export interface DevframeDockPreferences {
  categoryOrder?: Record<string, number>;
  maxVisibleItems?: number;
  defaultMode?: 'float' | 'edge';
  defaultPosition?: 'left' | 'right' | 'top' | 'bottom';
}
// #endregion

// #region Types
export type EmbeddedVisibility = 'normal' | 'passive' | 'hidden';
// #endregion

// #region Functions
export declare function createUi(_?: CreateUiOptions): DevframeHubUi;
// #endregion