import type { DevframeDefinition } from 'devframe/types'
import type { ClientScriptEntry } from '../types/docks'
import type { DevframeHubContext } from './context'
import type { DevframesInput, DockRendererRegistration, HubDevframeEntry } from './initiate'
import { existsSync } from 'node:fs'
import { DEVFRAME_CONNECTION_META_FILENAME, DEVFRAME_DOCK_IMPORTS_FILENAME, DEVFRAME_MCP_ROUTE, DEVFRAME_WS_ROUTE } from 'devframe/constants'
import { resolve } from 'pathe'
import { joinURL, withTrailingSlash } from 'ufo'
import { resolveClientModuleSpecifier } from '../client-modules'
import { diagnostics } from './diagnostics'
import { prepareDevframe } from './install-devframe'

/** Reserved filenames directly under the hub base; a frame id can't shadow them. */
const RESERVED_HUB_PATHS = [
  DEVFRAME_CONNECTION_META_FILENAME,
  DEVFRAME_DOCK_IMPORTS_FILENAME,
  DEVFRAME_WS_ROUTE,
  DEVFRAME_MCP_ROUTE,
  '__index.json',
  '__renderers',
  'embedded.js',
] as const

/** One resolved `devframes` slot: an entry, or nothing when it opted out. */
type ResolvedDevframeEntry = DevframeDefinition | HubDevframeEntry | null | undefined

function normalizeDevframeEntry(entry: DevframeDefinition | HubDevframeEntry): HubDevframeEntry {
  return 'devframe' in entry ? entry : { devframe: entry }
}

/**
 * Flatten the `devframes` input: await every thenable, call every factory,
 * spread the arrays, and drop the empty slots, so a host can build the list
 * conditionally (`isDev && loadInspect()`) without filtering it first.
 */
export function resolveDevframesInput(input: DevframesInput): Promise<HubDevframeEntry[]> {
  return Promise.all(input.map(async (entry) => {
    const resolved = await (typeof entry === 'function' ? entry() : entry)
    const slots: readonly ResolvedDevframeEntry[] = Array.isArray(resolved)
      ? resolved
      : [resolved as ResolvedDevframeEntry]
    return slots
      .filter((slot): slot is DevframeDefinition | HubDevframeEntry => slot != null)
      .map(normalizeDevframeEntry)
  }))
    .then(arrays => arrays.flat())
}

/**
 * Validate the renderer-module registrations fail-fast: route-safe types
 * (each becomes the `<base>__renderers/<type>.mjs` URL segment), one module
 * per type, and an existing bundle file (renderer packages are prebuilt).
 */
export function resolveRendererRegistrations(
  registrations: readonly DockRendererRegistration[],
): DockRendererRegistration[] {
  const seen = new Set<string>()
  return registrations.map((registration) => {
    if (!/^[\w.-]+$/.test(registration.type))
      throw diagnostics.DF8110({ type: registration.type })
    if (seen.has(registration.type))
      throw diagnostics.DF8108({ type: registration.type })
    seen.add(registration.type)
    const file = resolve(registration.file)
    if (!existsSync(file))
      throw diagnostics.DF8109({ type: registration.type, file })
    return { ...registration, file }
  })
}

/**
 * Render the dock client-script import map as an ES module: one dynamic
 * import thunk per dock that carries a client script (`clientScript` on
 * iframe docks, `action`, `renderer`). External viewers import this module
 * from `<base>__client-imports.js` to load per-dock client code into the
 * host page; `importFrom` values are URL paths the host serves, or bare npm
 * specifiers resolved through the host's `clientModuleResolution` template.
 */
export function renderClientImportsModule(ctx: DevframeHubContext): string {
  const template = ctx.staticConfig.dock?.clientModuleResolution
  const entries: string[] = []
  for (const [id, view] of ctx.docks.views) {
    const scripts: ClientScriptEntry[] = []
    const anyView = view as { clientScript?: ClientScriptEntry, action?: ClientScriptEntry, renderer?: ClientScriptEntry }
    if (anyView.clientScript)
      scripts.push(anyView.clientScript)
    if (anyView.action)
      scripts.push(anyView.action)
    if (anyView.renderer)
      scripts.push(anyView.renderer)
    if (scripts.length === 0)
      continue
    const thunks = scripts.map(script =>
      `() => import(${JSON.stringify(resolveClientModuleSpecifier(script.importFrom, { template }))})`)
    entries.push(`  ${JSON.stringify(id)}: [${thunks.join(', ')}],`)
  }
  return `// Generated by @devframes/hub: dock client-script import map.\nexport const clientImports = {\n${entries.join('\n')}\n}\nexport default clientImports\n`
}

/**
 * Pass 1: mount each devframe under `<base><id>/` (SPA, meta, iframe dock)
 * and queue its declared services, guarding the id against reserved hub
 * filenames and route-pattern characters. Returns the deferred setup thunks.
 */
export async function mountDevframes(
  ctx: DevframeHubContext,
  devframes: HubDevframeEntry[],
  base: string,
  frames: { id: string, base: string, title: string }[],
  hubMcpEnabled: boolean,
): Promise<(() => Promise<void>)[]> {
  const setups: (() => Promise<void>)[] = []
  for (const { devframe: def, dock } of devframes) {
    if ((RESERVED_HUB_PATHS as readonly string[]).includes(def.id))
      throw diagnostics.DF8000({ id: def.id })
    // The id becomes a URL segment (`<base><id>/`) routed by h3, where `:` and
    // `*` are route-pattern markers, and separators would escape the
    // segment entirely.
    if (!/^[\w.-]+$/.test(def.id))
      throw diagnostics.DF8004({ id: def.id })
    // A hub exposes one aggregate MCP route over every mounted devframe, so a
    // devframe's own `mcp` request is only meaningful when the hub's own MCP is
    // enabled. Warn when it isn't, rather than silently dropping the devframe's
    // intended agent surface.
    if (!hubMcpEnabled && def.cli?.mcp)
      diagnostics.DF8005({ id: def.id })
    const frameBase = withTrailingSlash(joinURL(base, def.id))
    const run = await prepareDevframe(ctx, def, { base: frameBase, ...(dock ? { dock } : {}) })
    if (run)
      setups.push(run)
    frames.push({ id: def.id, base: frameBase, title: def.name })
  }
  return setups
}
