/**
 * Generated by tsnapi — public API snapshot of `devframe/recipes/common-rpc-functions`
 */
// #region Types
export type KnownEditor = 'atom' | 'subl' | 'sublime' | 'sublime_text' | 'wstorm' | 'charm' | 'zed' | 'notepad++' | 'vim' | 'mvim' | 'joe' | 'gvim' | 'emacs' | 'emacsclient' | 'rmate' | 'mate' | 'code' | 'code-insiders' | 'codium' | 'vscodium' | 'trae' | 'antigravity' | 'cursor' | 'appcode' | 'clion' | 'idea' | 'phpstorm' | 'pycharm' | 'rubymine' | 'webstorm' | 'goland' | 'rider';
// #endregion

// #region Variables
/** @deprecated */
export declare const commonRpcFunctions: readonly [{
  name: "devframe:open-in-editor";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [SimpleSchema<string, string>, SimpleSchema<KnownEditor | undefined, KnownEditor | undefined>];
  returns: SimpleSchema<void, void>;
  jsonSerializable?: boolean;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string, KnownEditor | undefined], Thenable<void>>>) | undefined;
  handler?: ((args_0: string, args_1: KnownEditor | undefined) => Thenable<void>) | undefined;
  dump?: RpcDump<[string, KnownEditor | undefined], Thenable<void>, undefined> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, Thenable<RpcFunctionSetupResult<[string, KnownEditor | undefined], Thenable<void>>>> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string, KnownEditor | undefined], Thenable<void>>> | undefined;
}, {
  name: "devframe:open-in-finder";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [SimpleSchema<string, string>];
  returns: SimpleSchema<void, void>;
  jsonSerializable?: boolean;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string], Thenable<void>>>) | undefined;
  handler?: ((args_0: string) => Thenable<void>) | undefined;
  dump?: RpcDump<[string], Thenable<void>, undefined> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, Thenable<RpcFunctionSetupResult<[string], Thenable<void>>>> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string], Thenable<void>>> | undefined;
}];
export declare const KNOWN_EDITORS: KnownEditor[];
/** @deprecated */
export declare const openInEditor: {
  name: "devframe:open-in-editor";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [SimpleSchema<string, string>, SimpleSchema<KnownEditor | undefined, KnownEditor | undefined>];
  returns: SimpleSchema<void, void>;
  jsonSerializable?: boolean;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string, KnownEditor | undefined], Thenable<void>>>) | undefined;
  handler?: ((args_0: string, args_1: KnownEditor | undefined) => Thenable<void>) | undefined;
  dump?: RpcDump<[string, KnownEditor | undefined], Thenable<void>, undefined> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, Thenable<RpcFunctionSetupResult<[string, KnownEditor | undefined], Thenable<void>>>> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string, KnownEditor | undefined], Thenable<void>>> | undefined;
};
/** @deprecated */
export declare const openInFinder: {
  name: "devframe:open-in-finder";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [SimpleSchema<string, string>];
  returns: SimpleSchema<void, void>;
  jsonSerializable?: boolean;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string], Thenable<void>>>) | undefined;
  handler?: ((args_0: string) => Thenable<void>) | undefined;
  dump?: RpcDump<[string], Thenable<void>, undefined> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, Thenable<RpcFunctionSetupResult<[string], Thenable<void>>>> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string], Thenable<void>>> | undefined;
};
// #endregion