/**
 * Generated by tsnapi — public API snapshot of `devframe/recipes/interactive-auth`
 */
// #region Interfaces
export interface CreateAuthBannerColorsOptions {
  border: ColorFn;
  title: ColorFn;
  label: ColorFn;
  code: ColorFn;
  url: ColorFn;
}
export interface CreateAuthBannerOptions {
  title?: string;
  colors?: Partial<CreateAuthBannerColorsOptions>;
}
export interface CreateInteractiveAuthOptions {
  clientAuthTokens?: string[];
  banner?: AuthBannerFunction;
  onTrusted?: (_: {
    session: DevframeNodeRpcSession;
    authToken: string;
  }) => void;
  serverUrl?: () => string;
}
// #endregion

// #region Types
export type AuthBannerFunction = (_: {
  code: string;
  url: string;
}) => void;
// #endregion

// #region Functions
export declare function createAuthBanner(_?: CreateAuthBannerOptions): AuthBannerFunction;
export declare function createInteractiveAuth(_: DevframeNodeContext, _?: CreateInteractiveAuthOptions): DevframeAuthHandler;
// #endregion