/**
 * Generated by tsnapi — public API snapshot of `devframe/recipes/open-helpers`
 */
// #region Variables
export declare const openHelpers: readonly [{
  name: "devframe:open-in-editor";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [v.StringSchema<undefined>];
  returns: v.VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string], Thenable<void>>>) | undefined;
  handler?: ((args_0: string) => Thenable<void>) | undefined;
  dump?: RpcDump<[string], Thenable<void>, undefined> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, Thenable<RpcFunctionSetupResult<[string], Thenable<void>>>> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string], Thenable<void>>> | undefined;
}, {
  name: "devframe:open-in-finder";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [v.StringSchema<undefined>];
  returns: v.VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string], Thenable<void>>>) | undefined;
  handler?: ((args_0: string) => Thenable<void>) | undefined;
  dump?: RpcDump<[string], Thenable<void>, undefined> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, Thenable<RpcFunctionSetupResult<[string], Thenable<void>>>> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string], Thenable<void>>> | undefined;
}];
export declare const openInEditor: {
  name: "devframe:open-in-editor";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [v.StringSchema<undefined>];
  returns: v.VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string], Thenable<void>>>) | undefined;
  handler?: ((args_0: string) => Thenable<void>) | undefined;
  dump?: RpcDump<[string], Thenable<void>, undefined> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, Thenable<RpcFunctionSetupResult<[string], Thenable<void>>>> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string], Thenable<void>>> | undefined;
};
export declare const openInFinder: {
  name: "devframe:open-in-finder";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [v.StringSchema<undefined>];
  returns: v.VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string], Thenable<void>>>) | undefined;
  handler?: ((args_0: string) => Thenable<void>) | undefined;
  dump?: RpcDump<[string], Thenable<void>, undefined> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, Thenable<RpcFunctionSetupResult<[string], Thenable<void>>>> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string], Thenable<void>>> | undefined;
};
// #endregion