/**
 * Generated by tsnapi — public API snapshot of `devframe/recipes/open-helpers`
 */
// #region Variables
/** @deprecated */
export declare const openHelpers: typeof commonRpcFunctions;
export declare const openInEditor: {
  name: "devframe:open-in-editor";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [DevframeSchema<string, string>, DevframeSchema<KnownEditor | undefined, KnownEditor | undefined>];
  returns: DevframeSchema<void, void>;
  jsonSerializable?: boolean;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string, KnownEditor | undefined], void>>) | undefined;
  handler?: ((args_0: string, args_1: KnownEditor | undefined) => void) | undefined;
  dump?: RpcDump<[string, KnownEditor | undefined], void, undefined> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, Thenable<RpcFunctionSetupResult<[string, KnownEditor | undefined], void>>> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string, KnownEditor | undefined], void>> | undefined;
};
export declare const openInFinder: {
  name: "devframe:open-in-finder";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [DevframeSchema<string, string>];
  returns: DevframeSchema<void, void>;
  jsonSerializable?: boolean;
  agent?: RpcFunctionAgentOptions;
  setup?: ((context: undefined) => Thenable<RpcFunctionSetupResult<[string], void>>) | undefined;
  handler?: ((args_0: string) => void) | undefined;
  dump?: RpcDump<[string], void, undefined> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, Thenable<RpcFunctionSetupResult<[string], void>>> | undefined;
  __promise?: Thenable<RpcFunctionSetupResult<[string], void>> | undefined;
};
// #endregion