/**
 * Generated by tsnapi — public API snapshot of `@devframes/agentic/connect`
 */
// #region Interfaces
export interface ConnectServerHandle {
  stop: () => Promise<void>;
}
export interface ConnectServerOptions {
  ports?: number[];
  instancesDir?: string;
  timeoutMs?: number;
  authToken?: string | ((_: DevframeInstanceRecord) => string | undefined);
}
// #endregion

// #region Functions
export declare function buildInstanceRequestHeaders(_: string, _: string | undefined): Record<string, string>;
export declare function resolveAuthToken(_: ConnectServerOptions['authToken'], _: DevframeInstanceRecord): string | undefined;
export declare function startConnectServer(_?: ConnectServerOptions): Promise<ConnectServerHandle>;
// #endregion