/**
 * Generated by tsnapi — public API snapshot of `@devframes/agentic/mcp`
 */
// #region Functions
export declare function createMcpFetchHandler(_: DevframeNodeContext, _: CreateMcpFetchHandlerOptions$1): McpFetchHandler$1;
export declare function createMcpServer(_: DevframeDefinition, _?: CreateMcpServerOptions$1): Promise<McpServerHandle$1>;
export declare function mountMcpHttp(_: H3, _: DevframeNodeContext, _: string, _: MountMcpHttpOptions$1): MountedMcpHttp$1;
// #endregion

// #region Other
export { CreateMcpFetchHandlerOptions }
export { CreateMcpServerOptions }
export { McpConnectionInfo }
export { McpFetchHandler }
export { McpServerHandle }
export { MountedMcpHttp }
export { MountMcpHttpOptions }
// #endregion