/**
 * Generated by tsnapi — public API snapshot of `devframe/adapters/build`
 */
// #region Interfaces
export interface CreateBuildOptions {
  outDir?: string;
  distDir?: string;
  pretty?: boolean;
  force?: boolean;
}
// #endregion

// #region Functions
export declare function createBuild(_: DevframeDefinition, _?: CreateBuildOptions): Promise<void>;
// #endregion