/**
 * Generated by tsnapi — public API snapshot of `devframe/adapters/cac`
 */
// #region Interfaces
export interface CacHandle {
  cli: CAC;
  parse: (_?: string[]) => Promise<void>;
}
export interface CreateCacOptions {
  defaultPort?: number;
  configureCli?: (_: CAC) => void;
  onReady?: (_: {
    origin: string;
    port: number;
    app: H3;
  }) => void | Promise<void>;
}
// #endregion

// #region Functions
export declare function createCac(_: DevframeDefinition, _?: CreateCacOptions): CacHandle;
// #endregion

// #region Other
export { CliFlagsSchema }
export { defineCliFlags }
export { InferCliFlags }
export { parseCliFlags }
// #endregion