/**
 * Generated by tsnapi — public API snapshot of `devframe/adapters/dev`
 */
// #region Interfaces
export interface CreateDevServerOptions {
  host?: string;
  port?: number;
  flags?: Record<string, unknown>;
  distDir?: string;
  basePath?: string;
  ws?: DevframeWsOptions;
  app?: H3;
  openBrowser?: boolean | string;
  auth?: boolean | DevframeAuthHandler;
  mcp?: boolean | McpRouteOptions;
  onPeerConnect?: (_: Peer, _: DevframeNodeRpcSession) => void;
  onPeerDisconnect?: (_: Peer, _: DevframeNodeRpcSessionMeta) => void;
  onReady?: (_: {
    origin: string;
    port: number;
    app: H3;
  }) => void | Promise<void>;
}
// #endregion

// #region Functions
export declare function createDevServer(_: DevframeDefinition, _?: CreateDevServerOptions): Promise<StartedServer>;
// #endregion

// #region Other
export { resolveDevServerPort }
export { ResolveDevServerPortOptions }
export { resolveMcpConnectionMeta }
// #endregion