/**
 * Generated by tsnapi — public API snapshot of `devframe/adapters/flags`
 */
// #region Other
export { CliFlagsSchema }
export { defineCliFlags }
export { flagKeyToOption }
export { InferCliFlags }
export { isBooleanFlag }
export { parseCliFlags }
// #endregion