/**
 * Generated by tsnapi — public API snapshot of `devframe/adapters/mcp`
 */
// #region Functions
export declare function createMcpFetchHandler(_: DevframeNodeContext, _: CreateMcpFetchHandlerOptions): Promise<McpFetchHandler>;
export declare function createMcpServer(_: DevframeDefinition, _?: CreateMcpServerOptions): Promise<McpServerHandle>;
export declare function mountMcpHttp(_: H3, _: DevframeNodeContext, _: string, _: MountMcpHttpOptions): Promise<MountedMcpHttp>;
// #endregion

// #region Other
export { CreateMcpFetchHandlerOptions }
export { CreateMcpServerOptions }
export { McpConnectionInfo }
export { McpFetchHandler }
export { McpServerHandle }
export { MountedMcpHttp }
export { MountMcpHttpOptions }
// #endregion