/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-assets/client`
 */
// #region Functions
export declare function connectAssets(_?: DevframeRpcClientOptions): Promise<import("devframe/client").DevframeRpcClient>;
// #endregion

// #region Other
export { AssetImageMeta }
export { AssetInfo }
export { AssetType }
export { CodeSnippet }
// #endregion