/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-assets`
 */
// #region Interfaces
export interface AssetsDevframeOptions {
  id?: string;
  name?: string;
  icon?: string;
  dir?: string;
  baseURL?: string;
  serveStatic?: boolean;
  basePath?: string;
  distDir?: string;
  port?: number;
  write?: boolean;
  uploadExtensions?: readonly string[] | '*';
  watch?: boolean;
  auth?: boolean;
  build?: boolean;
}
// #endregion

// #region Functions
export declare function createAssetsDevframe(_?: AssetsDevframeOptions): DevframeDefinition;
// #endregion

// #region Default Export
declare function _default(_?: AssetsDevframeOptions): DevframeDefinition;
export default _default
// #endregion

// #region Other
export { AssetImageMeta }
export { AssetInfo }
export { AssetType }
export { CodeSnippet }
export { DEFAULT_ALLOWED_UPLOAD_EXTENSIONS }
// #endregion