/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-assets/vite`
 */
// #region Types
export type AssetsVitePluginOptions = DevframeViteOptions;
// #endregion

// #region Functions
export declare function assetsVitePlugin(_?: AssetsVitePluginOptions): DevframeVitePlugin;
// #endregion

// #region Other
export { DevframeViteOptions }
// #endregion