/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-code-server/cli`
 */
// #region Functions
export declare function createCodeServerCli(_?: CodeServerOptions, _?: CreateCliOptions): CliHandle;
// #endregion