/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-code-server/client`
 */
// #region Interfaces
export interface CodeServerHandle {
  rpc: DevframeRpcClient;
  dispose: () => void;
}
export interface MountCodeServerOptions {
  rpc?: DevframeRpcClient;
}
// #endregion

// #region Functions
export declare function mountCodeServer(_: HTMLElement, _?: MountCodeServerOptions): Promise<CodeServerHandle>;
// #endregion

// #region Other
export { CodeServerServerInfo }
export { CodeServerSharedState }
export { CodeServerStatus }
export { STATE_KEY }
// #endregion