/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-code-server/client`
 */
// #region Interfaces
export interface CodeServerHandle {
  rpc: DevframeRpcClient;
  stop: () => Promise<void>;
  dispose: () => void;
}
export interface CodeServerViewActions {
  launch: () => void;
  recheck: () => void;
}
export interface CodeServerViewHandle {
  update: (_: CodeServerViewState) => void;
  dispose: () => void;
}
export interface CodeServerViewOptions {
  actions?: Partial<CodeServerViewActions>;
  resolveEditorUrl?: (_: number) => string;
  applyAuth?: (_: CodeServerAuth) => void;
}
export interface CodeServerViewState {
  detection: CodeServerDetection;
  server: CodeServerServerInfo;
  auth?: CodeServerAuth;
  busy?: boolean;
}
export interface MountCodeServerOptions {
  rpc?: DevframeRpcClient;
}
// #endregion

// #region Types
export type CodeServerPhase = 'connecting' | 'not-installed' | 'launch' | 'starting' | 'running';
// #endregion

// #region Functions
export declare function createCodeServerView(_: HTMLElement, _?: CodeServerViewOptions): CodeServerViewHandle;
export declare function mountCodeServer(_: HTMLElement, _?: MountCodeServerOptions): Promise<CodeServerHandle>;
export declare function resolvePhase(_: CodeServerViewState): CodeServerPhase;
// #endregion

// #region Other
export { CodeServerServerInfo }
export { CodeServerSharedState }
export { CodeServerStatus }
export { STATE_KEY }
// #endregion