/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-code-server/client`
 */
// #region Functions
export declare function connectCodeServer(_?: DevframeRpcClientOptions): Promise<DevframeRpcClient>;
// #endregion

// #region Other
export { CodeServerBackend }
export { CodeServerConnect }
export { CodeServerDetection }
export { CodeServerLogin }
export { CodeServerMode }
export { CodeServerServerInfo }
export { CodeServerSharedState }
export { CodeServerStartResult }
export { CodeServerStatus }
export { CodeServerStatusResult }
export { DevframeConnectionStatus }
export { DevframeRpcClient }
export { STATE_KEY }
// #endregion