/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-code-server/constants`
 */
// #region Functions
export declare function getCookieSessionName(_?: string): string;
// #endregion

// #region Variables
export declare const DEFAULT_CODE_SERVER_PORT: number;
export declare const DEFAULT_PORT: number;
export declare const DEFAULT_START_TIMEOUT: number;
export declare const PLUGIN_ID: string;
export declare const SESSION_COOKIE_BASE: string;
export declare const STATE_KEY: string;
export declare const TERMINAL_SESSION_ICON: string;
export declare const TERMINAL_SESSION_TITLE: string;
// #endregion