/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-code-server`
 */
// #region Functions
export declare function createCodeServerDevframe(_?: CodeServerOptions): DevframeDefinition;
// #endregion

// #region Default Export
declare const _default: DevframeDefinition;
export default _default
// #endregion

// #region Other
export { CodeServerAuth }
export { CodeServerDetection }
export { CodeServerOptions }
export { CodeServerServerInfo }
export { CodeServerSharedState }
export { CodeServerStartRequest }
export { CodeServerStartResult }
export { CodeServerStatus }
export { CodeServerStatusResult }
export { DEFAULT_CODE_SERVER_PORT }
export { DEFAULT_PORT }
export { getCookieSessionName }
export { PLUGIN_ID }
export { STATE_KEY }
// #endregion