/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-code-server/node`
 */
// #region Classes
export declare class CodeServerSupervisor {
  private readonly ctx;
  private readonly bin;
  private readonly workspace;
  private readonly host;
  private readonly forcedPort?;
  private readonly extraArgs;
  private readonly extraEnv;
  private readonly cookieName;
  private readonly cookieSuffix?;
  private readonly startTimeout;
  private state?;
  private detection;
  private server;
  private proc?;
  private cookieValue?;
  private logBuffer;
  private cleanupRegistered;
  private readonly sessionId;
  private session?;
  constructor(_: DevframeNodeContext, _?: CodeServerOptions);
  init(): Promise<void>;
  detect(): Promise<CodeServerDetection>;
  status(): CodeServerStatusResult;
  start(_?: CodeServerStartRequest): Promise<CodeServerStartResult>;
  stop(): CodeServerStatusResult;
  dispose(): void;
  private authInfo;
  private terminate;
  private resolveHubTerminals;
  private reflectHub;
  private launchProcess;
  private appendLog;
  private lastLog;
  private publish;
  private waitForReady;
  private registerCleanup;
}
// #endregion

// #region Functions
export declare function detectCodeServer(_?: string, _?: number): Promise<DetectCodeServerResult>;
export declare function getCodeServerSupervisor(_: DevframeNodeContext): CodeServerSupervisor;
export declare function setCodeServerSupervisor(_: DevframeNodeContext, _: CodeServerSupervisor): void;
export declare function setupCodeServer(_: DevframeNodeContext, _?: CodeServerOptions): Promise<CodeServerSupervisor>;
// #endregion

// #region Variables
export declare const diagnostics: _$nostics.Diagnostics<{
  readonly DP_CODE_SERVER_0001: {
    readonly why: (p: {
      bin: string;
    }) => string;
    readonly fix: "Install code-server — e.g. `curl -fsSL https://code-server.dev/install.sh | sh` — or set the `bin` option to its path. See https://coder.com/docs/code-server/latest/install";
  };
  readonly DP_CODE_SERVER_0002: {
    readonly why: (p: {
      port: number;
      timeout: number;
    }) => string;
    readonly fix: "Check the code-server logs for startup errors, raise `startTimeout`, or free the port.";
  };
  readonly DP_CODE_SERVER_0003: {
    readonly why: (p: {
      bin: string;
      reason: string;
    }) => string;
  };
  readonly DP_CODE_SERVER_0004: {
    readonly why: "code-server supervisor is not initialised on this context";
    readonly fix: "Call setupCodeServer(ctx) (or use createCodeServerDevframe) before invoking the code-server RPCs.";
  };
  readonly DP_CODE_SERVER_0005: {
    readonly why: (p: {
      code: number;
    }) => string;
    readonly fix: "Inspect the captured output in the launcher and re-launch.";
  };
}, readonly [typeof reporter]>;
// #endregion