/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-code-server/node`
 */
// #region Classes
export declare class CodeServerSupervisor {
  private readonly ctx;
  private readonly bin;
  private readonly workspace;
  private readonly host;
  private readonly forcedPort?;
  private readonly extraArgs;
  private readonly extraEnv;
  private readonly cookieName;
  private readonly cookieSuffix?;
  private readonly startTimeout;
  private state?;
  private detection;
  private server;
  private proc?;
  private cookieValue?;
  private logBuffer;
  private cleanupRegistered;
  constructor(_: DevframeNodeContext, _?: CodeServerOptions);
  init(): Promise<void>;
  detect(): Promise<CodeServerDetection>;
  status(): CodeServerStatusResult;
  start(_?: CodeServerStartRequest): Promise<CodeServerStartResult>;
  stop(): CodeServerStatusResult;
  dispose(): void;
  private authInfo;
  private terminate;
  private appendLog;
  private lastLog;
  private publish;
  private waitForReady;
  private registerCleanup;
}
// #endregion

// #region Functions
export declare function detectCodeServer(_?: string, _?: number): Promise<DetectCodeServerResult>;
export declare function getCodeServerSupervisor(_: DevframeNodeContext): CodeServerSupervisor;
export declare function setCodeServerSupervisor(_: DevframeNodeContext, _: CodeServerSupervisor): void;
export declare function setupCodeServer(_: DevframeNodeContext, _?: CodeServerOptions): Promise<CodeServerSupervisor>;
// #endregion

// #region Variables
export declare const diagnostics: {
  readonly DP_CODE_SERVER_0001: _$nostics.DiagnosticHandle<{
    bin: string;
  }, {
    method?: "log" | "warn" | "error" | undefined;
  }>;
  readonly DP_CODE_SERVER_0002: _$nostics.DiagnosticHandle<{
    port: number;
    timeout: number;
  }, {
    method?: "log" | "warn" | "error" | undefined;
  }>;
  readonly DP_CODE_SERVER_0003: _$nostics.DiagnosticHandle<{
    bin: string;
    reason: string;
  }, {
    method?: "log" | "warn" | "error" | undefined;
  }>;
  readonly DP_CODE_SERVER_0004: _$nostics.DiagnosticHandle<{}, {
    method?: "log" | "warn" | "error" | undefined;
  }>;
  readonly DP_CODE_SERVER_0005: _$nostics.DiagnosticHandle<{
    code: number;
  }, {
    method?: "log" | "warn" | "error" | undefined;
  }>;
};
// #endregion