/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-code-server/rpc`
 */
// #region Variables
export declare const serverFunctions: readonly [{
  name: "devframes-plugin-code-server:detect";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$devframe.DevframeNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<CodeServerDetection>>>) | undefined;
  handler?: (() => Promise<CodeServerDetection>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[], Promise<CodeServerDetection>, _$devframe.DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<CodeServerDetection>>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<CodeServerDetection>>> | undefined;
}, {
  name: "devframes-plugin-code-server:status";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$devframe.DevframeNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], CodeServerStatusResult>>) | undefined;
  handler?: (() => CodeServerStatusResult) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[], CodeServerStatusResult, _$devframe.DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], CodeServerStatusResult>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], CodeServerStatusResult>> | undefined;
}, {
  name: "devframes-plugin-code-server:start";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$devframe.DevframeNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[req?: CodeServerStartRequest | undefined], Promise<CodeServerStatusResult>>>) | undefined;
  handler?: ((req?: CodeServerStartRequest | undefined) => Promise<CodeServerStatusResult>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[req?: CodeServerStartRequest | undefined], Promise<CodeServerStatusResult>, _$devframe.DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[req?: CodeServerStartRequest | undefined], Promise<CodeServerStatusResult>>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[req?: CodeServerStartRequest | undefined], Promise<CodeServerStatusResult>>> | undefined;
}, {
  name: "devframes-plugin-code-server:stop";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$devframe.DevframeNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], CodeServerStatusResult>>) | undefined;
  handler?: (() => CodeServerStatusResult) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[], CodeServerStatusResult, _$devframe.DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], CodeServerStatusResult>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], CodeServerStatusResult>> | undefined;
}];
// #endregion