/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-code-server/rpc`
 */
// #region Variables
export declare const serverFunctions: readonly [{
  name: "devframes-plugin-code-server:detect";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], Promise<CodeServerDetection>>>) | undefined;
  handler?: (() => Promise<CodeServerDetection>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[], Promise<CodeServerDetection>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], Promise<CodeServerDetection>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], Promise<CodeServerDetection>>> | undefined;
}, {
  name: "devframes-plugin-code-server:status";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], CodeServerStatusResult>>) | undefined;
  handler?: (() => CodeServerStatusResult) | undefined;
  dump?: import("devframe/rpc").RpcDump<[], CodeServerStatusResult, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], CodeServerStatusResult>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], CodeServerStatusResult>> | undefined;
}, {
  name: "devframes-plugin-code-server:start";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[req?: CodeServerStartRequest | undefined], Promise<CodeServerStatusResult>>>) | undefined;
  handler?: ((req?: CodeServerStartRequest | undefined) => Promise<CodeServerStatusResult>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[req?: CodeServerStartRequest | undefined], Promise<CodeServerStatusResult>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[req?: CodeServerStartRequest | undefined], Promise<CodeServerStatusResult>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[req?: CodeServerStartRequest | undefined], Promise<CodeServerStatusResult>>> | undefined;
}, {
  name: "devframes-plugin-code-server:stop";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], CodeServerStatusResult>>) | undefined;
  handler?: (() => CodeServerStatusResult) | undefined;
  dump?: import("devframe/rpc").RpcDump<[], CodeServerStatusResult, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], CodeServerStatusResult>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], CodeServerStatusResult>> | undefined;
}];
// #endregion