/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-code-server/types`
 */
// #region Interfaces
export interface CodeServerAuth {
  cookieName: string;
  cookieValue: string;
}
export interface CodeServerDetection {
  checked: boolean;
  installed: boolean;
  version?: string;
  bin: string;
}
export interface CodeServerOptions {
  bin?: string;
  cwd?: string;
  serverPort?: number;
  host?: string;
  args?: string[];
  env?: Record<string, string>;
  cookieSuffix?: string;
  startTimeout?: number;
  basePath?: string;
  distDir?: string;
  command?: string;
  port?: number;
}
export interface CodeServerServerInfo {
  status: CodeServerStatus;
  port?: number;
  startedAt?: number;
  pid?: number;
  error?: string;
}
export interface CodeServerSharedState {
  detection: CodeServerDetection;
  server: CodeServerServerInfo;
}
export interface CodeServerStartRequest {
  folder?: string;
}
export interface CodeServerStatusResult extends CodeServerSharedState {
  auth?: CodeServerAuth;
}
// #endregion

// #region Types
export type CodeServerStartResult = CodeServerStatusResult;
export type CodeServerStatus = 'stopped' | 'starting' | 'running' | 'error';
// #endregion