/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-code-server/vite`
 */
// #region Interfaces
export interface CodeServerViteOptions extends CodeServerOptions {
  vite?: ViteDevBridgeOptions;
}
// #endregion

// #region Functions
export declare function codeServerVite(_?: CodeServerViteOptions): DevframeVitePlugin[];
// #endregion