/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-a11y/client-script`
 */
// #region Default Export
declare function _default(_?: A11yPageScriptContext): void;
export default _default
// #endregion

// #region Referenced (internal)
interface A11yPageScriptContext {
  messages?: HubMessagesClient;
}
// #endregion