/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-a11y/client`
 */
// #region Functions
export declare function connectA11y(_?: DevframeRpcClientOptions): Promise<DevframeRpcClient>;
// #endregion

// #region Other
export { DevframeRpcClient }
export { Impact }
export { ScanReport }
export { Violation }
export { ViolationNode }
// #endregion