/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-a11y`
 */
// #region Interfaces
export interface A11yDevframeOptions {
  id?: string;
  name?: string;
  icon?: string;
  basePath?: string;
  port?: number;
  autoScan?: boolean;
  logIssues?: boolean;
  defaultHighlight?: boolean;
  axe?: {
    tags?: string[];
    runOptions?: Record<string, unknown>;
  };
}
export interface ScanReport {
  route: string;
  url: string;
  scannedAt: number;
  engine: string;
  violations: Violation[];
  counts: Record<Impact, number>;
}
export interface Violation {
  ruleId: string;
  impact: Impact;
  help: string;
  description: string;
  helpUrl: string;
  tags?: string[];
  bestPractice?: boolean;
  nodes: ViolationNode[];
}
export interface ViolationNode {
  id: string;
  target: string[];
  html: string;
  failureSummary: string;
}
// #endregion

// #region Types
export type Impact = (typeof IMPACT_ORDER)[number];
// #endregion

// #region Functions
export declare function createA11yDevframe(_?: A11yDevframeOptions): DevframeDefinition;
// #endregion

// #region Variables
export declare const a11yAgentBundlePath: string;
// #endregion

// #region Default Export
declare const _default: DevframeDefinition;
export default _default
// #endregion