/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-a11y/node`
 */
// #region Functions
export declare function setupA11y(_: DevframeNodeContext, _?: A11yRuntimeConfig): void;
// #endregion

// #region Other
export { serverFunctions }
// #endregion