/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-a11y/vite`
 */
// #region Interfaces
export interface A11yAgentOptions {
  path?: string;
  inject?: boolean;
}
// #endregion

// #region Functions
export declare function a11yAgent(_?: A11yAgentOptions): Plugin;
export declare function a11yVitePlugin(_?: ViteDevBridgeOptions): DevframeVitePlugin;
// #endregion

// #region Other
export { ViteDevBridgeOptions }
// #endregion