/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-a11y/vite`
 */
// #region Functions
export declare function a11yVitePlugin(_?: ViteDevBridgeOptions): DevframeVitePlugin;
// #endregion

// #region Other
export { ViteDevBridgeOptions }
// #endregion