/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-inspect/client`
 */
// #region Functions
export declare function connectInspect(_?: DevframeRpcClientOptions): Promise<DevframeRpcClient>;
// #endregion

// #region Other
export { AgentManifest }
export { DevframeRpcClient }
export { InvokeResult }
export { RpcFunctionAgentInfo }
export { RpcFunctionInfo }
// #endregion