/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-inspect`
 */
// #region Default Export
export default createInspectDevframe
// #endregion

// #region Other
export { createInspectDevframe }
export { DevframeInspectCommandInfo }
export { InspectDevframeOptions }
export { InvokeResult }
export { RpcFunctionInfo }
// #endregion