/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-inspect`
 */
// #region Interfaces
export interface InspectDevframeOptions {
  id?: string;
  name?: string;
  icon?: string;
  basePath?: string;
  port?: number;
  auth?: boolean;
}
export interface InvokeResult {
  ok: boolean;
  result?: unknown;
  error?: {
    name: string;
    message: string;
    stack?: string;
  };
  durationMs: number;
}
export interface RpcFunctionInfo {
  name: string;
  type: 'query' | 'static' | 'action' | 'event';
  jsonSerializable: boolean;
  snapshot: boolean;
  cacheable: boolean;
  hasArgs: boolean;
  hasReturns: boolean;
  hasDump: boolean;
  hasSetup: boolean;
  hasHandler: boolean;
  invokable: boolean;
  agent?: RpcFunctionAgentInfo;
  argsSchema?: unknown;
  returnsSchema?: unknown;
}
// #endregion

// #region Functions
export declare function createInspectDevframe(_?: InspectDevframeOptions): DevframeDefinition;
// #endregion

// #region Default Export
declare const _default: DevframeDefinition;
export default _default
// #endregion