/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-inspect/node`
 */
// #region Functions
export declare function setupInspect(_: DevframeNodeContext): void;
// #endregion

// #region Other
export { serverFunctions }
// #endregion