/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-inspect/vite`
 */
// #region Functions
export declare function inspectVitePlugin(_?: ViteDevBridgeOptions): DevframeVitePlugin;
// #endregion

// #region Other
export { ViteDevBridgeOptions }
// #endregion