/**
 * Generated by tsnapi — public API snapshot of `@devframes/vite/hub/client`
 */
// #region Interfaces
export interface MountDevframeHubClientOptions extends DevframeClientHostOptions$1 {
  base?: string;
}
// #endregion

// #region Functions
export declare function mountDevframeHubClient(_?: MountDevframeHubClientOptions): Promise<DevframeClientHost$1>;
// #endregion

// #region Other
export { DevframeClientHost }
export { DevframeClientHostOptions }
// #endregion