/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-terminals/cli`
 */
// #region Functions
export declare function createTerminalsCli(_?: TerminalsOptions, _?: CreateCacOptions): CacHandle;
// #endregion