/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-terminals/constants`
 */
// #region Variables
export declare const DEFAULT_COLS: number;
export declare const DEFAULT_PORT: number;
export declare const DEFAULT_ROWS: number;
export declare const DEFAULT_SCROLLBACK: number;
export declare const HUB_TERMINAL_STREAM_CHANNEL: string;
export declare const PLUGIN_ID: string;
export declare const PRESETS_STATE_KEY: string;
export declare const SESSIONS_STATE_KEY: string;
export declare const TERMINAL_STREAM_CHANNEL: string;
// #endregion