/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-terminals`
 */
// #region Functions
export declare function createTerminalsDevframe(_?: TerminalsOptions): DevframeDefinition;
// #endregion

// #region Default Export
declare const _default: DevframeDefinition;
export default _default
// #endregion

// #region Other
export { DEFAULT_PORT }
export { PLUGIN_ID }
export { PRESETS_STATE_KEY }
export { SESSIONS_STATE_KEY }
export { SpawnRequest }
export { TERMINAL_STREAM_CHANNEL }
export { TerminalBackend }
export { TerminalMode }
export { TerminalPreset }
export { TerminalSessionInfo }
export { TerminalsOptions }
export { TerminalsSharedState }
export { TerminalStatus }
// #endregion