/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-terminals/rpc`
 */
// #region Variables
export declare const serverFunctions: readonly [{
  name: "devframes:plugin:terminals:list";
  type?: "query" | undefined;
  cacheable?: boolean;
  args: readonly [];
  returns: import("valibot").ArraySchema<import("valibot").ObjectSchema<{
    readonly id: import("valibot").StringSchema<undefined>;
    readonly title: import("valibot").StringSchema<undefined>;
    readonly processName: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly customTitle: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly mode: import("valibot").PicklistSchema<["interactive", "readonly"], undefined>;
    readonly status: import("valibot").PicklistSchema<["running", "exited", "error"], undefined>;
    readonly backend: import("valibot").PicklistSchema<["pty", "pipe"], undefined>;
    readonly command: import("valibot").StringSchema<undefined>;
    readonly args: import("valibot").ArraySchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly cwd: import("valibot").StringSchema<undefined>;
    readonly cols: import("valibot").NumberSchema<undefined>;
    readonly rows: import("valibot").NumberSchema<undefined>;
    readonly pid: import("valibot").OptionalSchema<import("valibot").NumberSchema<undefined>, undefined>;
    readonly exitCode: import("valibot").OptionalSchema<import("valibot").NumberSchema<undefined>, undefined>;
    readonly icon: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly channel: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly presetId: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly createdAt: import("valibot").NumberSchema<undefined>;
  }, undefined>, undefined>;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }[]>>) | undefined;
  handler?: (() => {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }[]) | undefined;
  dump?: import("devframe/rpc").RpcDump<[], {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }[], import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }[]>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }[]>> | undefined;
}, {
  name: "devframes:plugin:terminals:presets";
  type?: "query" | undefined;
  cacheable?: boolean;
  args: readonly [];
  returns: import("valibot").ArraySchema<import("valibot").ObjectSchema<{
    readonly id: import("valibot").StringSchema<undefined>;
    readonly title: import("valibot").StringSchema<undefined>;
    readonly command: import("valibot").StringSchema<undefined>;
    readonly args: import("valibot").ArraySchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly mode: import("valibot").PicklistSchema<["interactive", "readonly"], undefined>;
    readonly icon: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
  }, undefined>, undefined>;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], {
    id: string;
    title: string;
    command: string;
    args: string[];
    mode: "interactive" | "readonly";
    icon?: string | undefined;
  }[]>>) | undefined;
  handler?: (() => {
    id: string;
    title: string;
    command: string;
    args: string[];
    mode: "interactive" | "readonly";
    icon?: string | undefined;
  }[]) | undefined;
  dump?: import("devframe/rpc").RpcDump<[], {
    id: string;
    title: string;
    command: string;
    args: string[];
    mode: "interactive" | "readonly";
    icon?: string | undefined;
  }[], import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], {
    id: string;
    title: string;
    command: string;
    args: string[];
    mode: "interactive" | "readonly";
    icon?: string | undefined;
  }[]>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], {
    id: string;
    title: string;
    command: string;
    args: string[];
    mode: "interactive" | "readonly";
    icon?: string | undefined;
  }[]>> | undefined;
}, {
  name: "devframes:plugin:terminals:spawn";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [import("valibot").ObjectSchema<{
    readonly presetId: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly command: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly args: import("valibot").OptionalSchema<import("valibot").ArraySchema<import("valibot").StringSchema<undefined>, undefined>, undefined>;
    readonly cwd: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly mode: import("valibot").OptionalSchema<import("valibot").PicklistSchema<["interactive", "readonly"], undefined>, undefined>;
    readonly title: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly cols: import("valibot").OptionalSchema<import("valibot").NumberSchema<undefined>, undefined>;
    readonly rows: import("valibot").OptionalSchema<import("valibot").NumberSchema<undefined>, undefined>;
    readonly env: import("valibot").OptionalSchema<import("valibot").RecordSchema<import("valibot").StringSchema<undefined>, import("valibot").StringSchema<undefined>, undefined>, undefined>;
  }, undefined>];
  returns: import("valibot").ObjectSchema<{
    readonly id: import("valibot").StringSchema<undefined>;
    readonly title: import("valibot").StringSchema<undefined>;
    readonly processName: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly customTitle: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly mode: import("valibot").PicklistSchema<["interactive", "readonly"], undefined>;
    readonly status: import("valibot").PicklistSchema<["running", "exited", "error"], undefined>;
    readonly backend: import("valibot").PicklistSchema<["pty", "pipe"], undefined>;
    readonly command: import("valibot").StringSchema<undefined>;
    readonly args: import("valibot").ArraySchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly cwd: import("valibot").StringSchema<undefined>;
    readonly cols: import("valibot").NumberSchema<undefined>;
    readonly rows: import("valibot").NumberSchema<undefined>;
    readonly pid: import("valibot").OptionalSchema<import("valibot").NumberSchema<undefined>, undefined>;
    readonly exitCode: import("valibot").OptionalSchema<import("valibot").NumberSchema<undefined>, undefined>;
    readonly icon: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly channel: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly presetId: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly createdAt: import("valibot").NumberSchema<undefined>;
  }, undefined>;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    presetId?: string | undefined;
    command?: string | undefined;
    args?: string[] | undefined;
    cwd?: string | undefined;
    mode?: "interactive" | "readonly" | undefined;
    title?: string | undefined;
    cols?: number | undefined;
    rows?: number | undefined;
    env?: {
      [x: string]: string;
    } | undefined;
  }], {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }>>) | undefined;
  handler?: ((args_0: {
    presetId?: string | undefined;
    command?: string | undefined;
    args?: string[] | undefined;
    cwd?: string | undefined;
    mode?: "interactive" | "readonly" | undefined;
    title?: string | undefined;
    cols?: number | undefined;
    rows?: number | undefined;
    env?: {
      [x: string]: string;
    } | undefined;
  }) => {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }) | undefined;
  dump?: import("devframe/rpc").RpcDump<[{
    presetId?: string | undefined;
    command?: string | undefined;
    args?: string[] | undefined;
    cwd?: string | undefined;
    mode?: "interactive" | "readonly" | undefined;
    title?: string | undefined;
    cols?: number | undefined;
    rows?: number | undefined;
    env?: {
      [x: string]: string;
    } | undefined;
  }], {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    presetId?: string | undefined;
    command?: string | undefined;
    args?: string[] | undefined;
    cwd?: string | undefined;
    mode?: "interactive" | "readonly" | undefined;
    title?: string | undefined;
    cols?: number | undefined;
    rows?: number | undefined;
    env?: {
      [x: string]: string;
    } | undefined;
  }], {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    presetId?: string | undefined;
    command?: string | undefined;
    args?: string[] | undefined;
    cwd?: string | undefined;
    mode?: "interactive" | "readonly" | undefined;
    title?: string | undefined;
    cols?: number | undefined;
    rows?: number | undefined;
    env?: {
      [x: string]: string;
    } | undefined;
  }], {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }>> | undefined;
}, {
  name: "devframes:plugin:terminals:write";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [import("valibot").ObjectSchema<{
    readonly id: import("valibot").StringSchema<undefined>;
    readonly data: import("valibot").StringSchema<undefined>;
  }, undefined>];
  returns: import("valibot").VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
    data: string;
  }], void>>) | undefined;
  handler?: ((args_0: {
    id: string;
    data: string;
  }) => void) | undefined;
  dump?: import("devframe/rpc").RpcDump<[{
    id: string;
    data: string;
  }], void, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
    data: string;
  }], void>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
    data: string;
  }], void>> | undefined;
}, {
  name: "devframes:plugin:terminals:resize";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [import("valibot").ObjectSchema<{
    readonly id: import("valibot").StringSchema<undefined>;
    readonly cols: import("valibot").SchemaWithPipe<readonly [import("valibot").NumberSchema<undefined>, import("valibot").IntegerAction<number, undefined>, import("valibot").MinValueAction<number, 1, undefined>]>;
    readonly rows: import("valibot").SchemaWithPipe<readonly [import("valibot").NumberSchema<undefined>, import("valibot").IntegerAction<number, undefined>, import("valibot").MinValueAction<number, 1, undefined>]>;
  }, undefined>];
  returns: import("valibot").VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
    cols: number;
    rows: number;
  }], void>>) | undefined;
  handler?: ((args_0: {
    id: string;
    cols: number;
    rows: number;
  }) => void) | undefined;
  dump?: import("devframe/rpc").RpcDump<[{
    id: string;
    cols: number;
    rows: number;
  }], void, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
    cols: number;
    rows: number;
  }], void>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
    cols: number;
    rows: number;
  }], void>> | undefined;
}, {
  name: "devframes:plugin:terminals:terminate";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [import("valibot").ObjectSchema<{
    readonly id: import("valibot").StringSchema<undefined>;
  }, undefined>];
  returns: import("valibot").VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
  }], void>>) | undefined;
  handler?: ((args_0: {
    id: string;
  }) => void) | undefined;
  dump?: import("devframe/rpc").RpcDump<[{
    id: string;
  }], void, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
  }], void>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
  }], void>> | undefined;
}, {
  name: "devframes:plugin:terminals:restart";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [import("valibot").ObjectSchema<{
    readonly id: import("valibot").StringSchema<undefined>;
  }, undefined>];
  returns: import("valibot").ObjectSchema<{
    readonly id: import("valibot").StringSchema<undefined>;
    readonly title: import("valibot").StringSchema<undefined>;
    readonly processName: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly customTitle: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly mode: import("valibot").PicklistSchema<["interactive", "readonly"], undefined>;
    readonly status: import("valibot").PicklistSchema<["running", "exited", "error"], undefined>;
    readonly backend: import("valibot").PicklistSchema<["pty", "pipe"], undefined>;
    readonly command: import("valibot").StringSchema<undefined>;
    readonly args: import("valibot").ArraySchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly cwd: import("valibot").StringSchema<undefined>;
    readonly cols: import("valibot").NumberSchema<undefined>;
    readonly rows: import("valibot").NumberSchema<undefined>;
    readonly pid: import("valibot").OptionalSchema<import("valibot").NumberSchema<undefined>, undefined>;
    readonly exitCode: import("valibot").OptionalSchema<import("valibot").NumberSchema<undefined>, undefined>;
    readonly icon: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly channel: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly presetId: import("valibot").OptionalSchema<import("valibot").StringSchema<undefined>, undefined>;
    readonly createdAt: import("valibot").NumberSchema<undefined>;
  }, undefined>;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
  }], {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }>>) | undefined;
  handler?: ((args_0: {
    id: string;
  }) => {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }) | undefined;
  dump?: import("devframe/rpc").RpcDump<[{
    id: string;
  }], {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
  }], {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
  }], {
    id: string;
    title: string;
    processName?: string | undefined;
    customTitle?: string | undefined;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    icon?: string | undefined;
    channel?: string | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }>> | undefined;
}, {
  name: "devframes:plugin:terminals:rename";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [import("valibot").ObjectSchema<{
    readonly id: import("valibot").StringSchema<undefined>;
    readonly title: import("valibot").StringSchema<undefined>;
  }, undefined>];
  returns: import("valibot").VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
    title: string;
  }], void>>) | undefined;
  handler?: ((args_0: {
    id: string;
    title: string;
  }) => void) | undefined;
  dump?: import("devframe/rpc").RpcDump<[{
    id: string;
    title: string;
  }], void, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
    title: string;
  }], void>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
    title: string;
  }], void>> | undefined;
}, {
  name: "devframes:plugin:terminals:remove";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [import("valibot").ObjectSchema<{
    readonly id: import("valibot").StringSchema<undefined>;
  }, undefined>];
  returns: import("valibot").VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
  }], void>>) | undefined;
  handler?: ((args_0: {
    id: string;
  }) => void) | undefined;
  dump?: import("devframe/rpc").RpcDump<[{
    id: string;
  }], void, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
  }], void>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[{
    id: string;
  }], void>> | undefined;
}, {
  name: "devframes:plugin:terminals:clear-exited";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [];
  returns: import("valibot").VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], void>>) | undefined;
  handler?: (() => void) | undefined;
  dump?: import("devframe/rpc").RpcDump<[], void, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], void>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], void>> | undefined;
}];
// #endregion