/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-terminals/rpc`
 */
// #region Variables
export declare const serverFunctions: readonly [{
  name: "devframes-plugin-terminals:list";
  type?: "query" | undefined;
  cacheable?: boolean;
  args: readonly [];
  returns: _$valibot.ArraySchema<_$valibot.ObjectSchema<{
    readonly id: _$valibot.StringSchema<undefined>;
    readonly title: _$valibot.StringSchema<undefined>;
    readonly mode: _$valibot.PicklistSchema<["interactive", "readonly"], undefined>;
    readonly status: _$valibot.PicklistSchema<["running", "exited", "error"], undefined>;
    readonly backend: _$valibot.PicklistSchema<["pty", "pipe"], undefined>;
    readonly command: _$valibot.StringSchema<undefined>;
    readonly args: _$valibot.ArraySchema<_$valibot.StringSchema<undefined>, undefined>;
    readonly cwd: _$valibot.StringSchema<undefined>;
    readonly cols: _$valibot.NumberSchema<undefined>;
    readonly rows: _$valibot.NumberSchema<undefined>;
    readonly pid: _$valibot.OptionalSchema<_$valibot.NumberSchema<undefined>, undefined>;
    readonly exitCode: _$valibot.OptionalSchema<_$valibot.NumberSchema<undefined>, undefined>;
    readonly presetId: _$valibot.OptionalSchema<_$valibot.StringSchema<undefined>, undefined>;
    readonly createdAt: _$valibot.NumberSchema<undefined>;
  }, undefined>, undefined>;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$devframe.DevframeNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }[]>>) | undefined;
  handler?: (() => {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }[]) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[], {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }[], _$devframe.DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }[]>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }[]>> | undefined;
}, {
  name: "devframes-plugin-terminals:presets";
  type?: "query" | undefined;
  cacheable?: boolean;
  args: readonly [];
  returns: _$valibot.ArraySchema<_$valibot.ObjectSchema<{
    readonly id: _$valibot.StringSchema<undefined>;
    readonly title: _$valibot.StringSchema<undefined>;
    readonly command: _$valibot.StringSchema<undefined>;
    readonly args: _$valibot.ArraySchema<_$valibot.StringSchema<undefined>, undefined>;
    readonly mode: _$valibot.PicklistSchema<["interactive", "readonly"], undefined>;
    readonly icon: _$valibot.OptionalSchema<_$valibot.StringSchema<undefined>, undefined>;
  }, undefined>, undefined>;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$devframe.DevframeNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], {
    id: string;
    title: string;
    command: string;
    args: string[];
    mode: "interactive" | "readonly";
    icon?: string | undefined;
  }[]>>) | undefined;
  handler?: (() => {
    id: string;
    title: string;
    command: string;
    args: string[];
    mode: "interactive" | "readonly";
    icon?: string | undefined;
  }[]) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[], {
    id: string;
    title: string;
    command: string;
    args: string[];
    mode: "interactive" | "readonly";
    icon?: string | undefined;
  }[], _$devframe.DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], {
    id: string;
    title: string;
    command: string;
    args: string[];
    mode: "interactive" | "readonly";
    icon?: string | undefined;
  }[]>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], {
    id: string;
    title: string;
    command: string;
    args: string[];
    mode: "interactive" | "readonly";
    icon?: string | undefined;
  }[]>> | undefined;
}, {
  name: "devframes-plugin-terminals:spawn";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [_$valibot.ObjectSchema<{
    readonly presetId: _$valibot.OptionalSchema<_$valibot.StringSchema<undefined>, undefined>;
    readonly command: _$valibot.OptionalSchema<_$valibot.StringSchema<undefined>, undefined>;
    readonly args: _$valibot.OptionalSchema<_$valibot.ArraySchema<_$valibot.StringSchema<undefined>, undefined>, undefined>;
    readonly cwd: _$valibot.OptionalSchema<_$valibot.StringSchema<undefined>, undefined>;
    readonly mode: _$valibot.OptionalSchema<_$valibot.PicklistSchema<["interactive", "readonly"], undefined>, undefined>;
    readonly title: _$valibot.OptionalSchema<_$valibot.StringSchema<undefined>, undefined>;
    readonly cols: _$valibot.OptionalSchema<_$valibot.NumberSchema<undefined>, undefined>;
    readonly rows: _$valibot.OptionalSchema<_$valibot.NumberSchema<undefined>, undefined>;
    readonly env: _$valibot.OptionalSchema<_$valibot.RecordSchema<_$valibot.StringSchema<undefined>, _$valibot.StringSchema<undefined>, undefined>, undefined>;
  }, undefined>];
  returns: _$valibot.ObjectSchema<{
    readonly id: _$valibot.StringSchema<undefined>;
    readonly title: _$valibot.StringSchema<undefined>;
    readonly mode: _$valibot.PicklistSchema<["interactive", "readonly"], undefined>;
    readonly status: _$valibot.PicklistSchema<["running", "exited", "error"], undefined>;
    readonly backend: _$valibot.PicklistSchema<["pty", "pipe"], undefined>;
    readonly command: _$valibot.StringSchema<undefined>;
    readonly args: _$valibot.ArraySchema<_$valibot.StringSchema<undefined>, undefined>;
    readonly cwd: _$valibot.StringSchema<undefined>;
    readonly cols: _$valibot.NumberSchema<undefined>;
    readonly rows: _$valibot.NumberSchema<undefined>;
    readonly pid: _$valibot.OptionalSchema<_$valibot.NumberSchema<undefined>, undefined>;
    readonly exitCode: _$valibot.OptionalSchema<_$valibot.NumberSchema<undefined>, undefined>;
    readonly presetId: _$valibot.OptionalSchema<_$valibot.StringSchema<undefined>, undefined>;
    readonly createdAt: _$valibot.NumberSchema<undefined>;
  }, undefined>;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$devframe.DevframeNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    presetId?: string | undefined;
    command?: string | undefined;
    args?: string[] | undefined;
    cwd?: string | undefined;
    mode?: "interactive" | "readonly" | undefined;
    title?: string | undefined;
    cols?: number | undefined;
    rows?: number | undefined;
    env?: {
      [x: string]: string;
    } | undefined;
  }], {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }>>) | undefined;
  handler?: ((args_0: {
    presetId?: string | undefined;
    command?: string | undefined;
    args?: string[] | undefined;
    cwd?: string | undefined;
    mode?: "interactive" | "readonly" | undefined;
    title?: string | undefined;
    cols?: number | undefined;
    rows?: number | undefined;
    env?: {
      [x: string]: string;
    } | undefined;
  }) => {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[{
    presetId?: string | undefined;
    command?: string | undefined;
    args?: string[] | undefined;
    cwd?: string | undefined;
    mode?: "interactive" | "readonly" | undefined;
    title?: string | undefined;
    cols?: number | undefined;
    rows?: number | undefined;
    env?: {
      [x: string]: string;
    } | undefined;
  }], {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }, _$devframe.DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    presetId?: string | undefined;
    command?: string | undefined;
    args?: string[] | undefined;
    cwd?: string | undefined;
    mode?: "interactive" | "readonly" | undefined;
    title?: string | undefined;
    cols?: number | undefined;
    rows?: number | undefined;
    env?: {
      [x: string]: string;
    } | undefined;
  }], {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    presetId?: string | undefined;
    command?: string | undefined;
    args?: string[] | undefined;
    cwd?: string | undefined;
    mode?: "interactive" | "readonly" | undefined;
    title?: string | undefined;
    cols?: number | undefined;
    rows?: number | undefined;
    env?: {
      [x: string]: string;
    } | undefined;
  }], {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }>> | undefined;
}, {
  name: "devframes-plugin-terminals:write";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [_$valibot.ObjectSchema<{
    readonly id: _$valibot.StringSchema<undefined>;
    readonly data: _$valibot.StringSchema<undefined>;
  }, undefined>];
  returns: _$valibot.VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$devframe.DevframeNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
    data: string;
  }], void>>) | undefined;
  handler?: ((args_0: {
    id: string;
    data: string;
  }) => void) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[{
    id: string;
    data: string;
  }], void, _$devframe.DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
    data: string;
  }], void>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
    data: string;
  }], void>> | undefined;
}, {
  name: "devframes-plugin-terminals:resize";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [_$valibot.ObjectSchema<{
    readonly id: _$valibot.StringSchema<undefined>;
    readonly cols: _$valibot.SchemaWithPipe<readonly [_$valibot.NumberSchema<undefined>, _$valibot.IntegerAction<number, undefined>, _$valibot.MinValueAction<number, 1, undefined>]>;
    readonly rows: _$valibot.SchemaWithPipe<readonly [_$valibot.NumberSchema<undefined>, _$valibot.IntegerAction<number, undefined>, _$valibot.MinValueAction<number, 1, undefined>]>;
  }, undefined>];
  returns: _$valibot.VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$devframe.DevframeNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
    cols: number;
    rows: number;
  }], void>>) | undefined;
  handler?: ((args_0: {
    id: string;
    cols: number;
    rows: number;
  }) => void) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[{
    id: string;
    cols: number;
    rows: number;
  }], void, _$devframe.DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
    cols: number;
    rows: number;
  }], void>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
    cols: number;
    rows: number;
  }], void>> | undefined;
}, {
  name: "devframes-plugin-terminals:terminate";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [_$valibot.ObjectSchema<{
    readonly id: _$valibot.StringSchema<undefined>;
  }, undefined>];
  returns: _$valibot.VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$devframe.DevframeNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
  }], void>>) | undefined;
  handler?: ((args_0: {
    id: string;
  }) => void) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[{
    id: string;
  }], void, _$devframe.DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
  }], void>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
  }], void>> | undefined;
}, {
  name: "devframes-plugin-terminals:restart";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [_$valibot.ObjectSchema<{
    readonly id: _$valibot.StringSchema<undefined>;
  }, undefined>];
  returns: _$valibot.ObjectSchema<{
    readonly id: _$valibot.StringSchema<undefined>;
    readonly title: _$valibot.StringSchema<undefined>;
    readonly mode: _$valibot.PicklistSchema<["interactive", "readonly"], undefined>;
    readonly status: _$valibot.PicklistSchema<["running", "exited", "error"], undefined>;
    readonly backend: _$valibot.PicklistSchema<["pty", "pipe"], undefined>;
    readonly command: _$valibot.StringSchema<undefined>;
    readonly args: _$valibot.ArraySchema<_$valibot.StringSchema<undefined>, undefined>;
    readonly cwd: _$valibot.StringSchema<undefined>;
    readonly cols: _$valibot.NumberSchema<undefined>;
    readonly rows: _$valibot.NumberSchema<undefined>;
    readonly pid: _$valibot.OptionalSchema<_$valibot.NumberSchema<undefined>, undefined>;
    readonly exitCode: _$valibot.OptionalSchema<_$valibot.NumberSchema<undefined>, undefined>;
    readonly presetId: _$valibot.OptionalSchema<_$valibot.StringSchema<undefined>, undefined>;
    readonly createdAt: _$valibot.NumberSchema<undefined>;
  }, undefined>;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$devframe.DevframeNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
  }], {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }>>) | undefined;
  handler?: ((args_0: {
    id: string;
  }) => {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[{
    id: string;
  }], {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }, _$devframe.DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
  }], {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
  }], {
    id: string;
    title: string;
    mode: "interactive" | "readonly";
    status: "running" | "exited" | "error";
    backend: "pty" | "pipe";
    command: string;
    args: string[];
    cwd: string;
    cols: number;
    rows: number;
    pid?: number | undefined;
    exitCode?: number | undefined;
    presetId?: string | undefined;
    createdAt: number;
  }>> | undefined;
}, {
  name: "devframes-plugin-terminals:remove";
  type?: "action" | undefined;
  cacheable?: boolean;
  args: readonly [_$valibot.ObjectSchema<{
    readonly id: _$valibot.StringSchema<undefined>;
  }, undefined>];
  returns: _$valibot.VoidSchema<undefined>;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: _$devframe.DevframeNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
  }], void>>) | undefined;
  handler?: ((args_0: {
    id: string;
  }) => void) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[{
    id: string;
  }], void, _$devframe.DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
  }], void>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[{
    id: string;
  }], void>> | undefined;
}];
// #endregion