/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-terminals/vite`
 */
// #region Interfaces
export interface TerminalsViteOptions extends TerminalsOptions {
  vite?: ViteDevBridgeOptions;
}
// #endregion

// #region Functions
export declare function terminalsVite(_?: TerminalsViteOptions): DevframeVitePlugin[];
// #endregion