/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-data-inspector/cli`
 */
// #region Interfaces
export interface StaticDataset {
  sources: Array<{
    id: string;
    title: string;
    description?: string;
    icon?: string;
    static: boolean;
    queries?: {
      query: string;
      title?: string;
      description?: string;
    }[];
    data: unknown;
  }>;
}
// #endregion

// #region Functions
export declare function createDataInspectorCli(): {
  cli: import("cac").CAC;
  parse: (_?: string[]) => Promise<void>;
};
// #endregion