/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-data-inspector/engine`
 */
// #region Other
export { DataSourceMeta }
export { FilterOptions }
export { isExcludedKey }
export { normalize }
export { NormalizeOptions }
export { NormalizeStats }
export { NormalizeStatsWire }
export { Query }
export { QueryOutcome }
export { QueryStats }
export { runQuery }
export { SavedQuery }
export { SavedQueryScope }
export { SaveQueryInput }
export { skeletonOf }
export { SkeletonOptions }
export { SkeletonOutcome }
export { suggest }
export { SuggestItem }
export { SuggestOutcome }
// #endregion