/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-data-inspector`
 */
// #region Interfaces
export interface DataInspectorDevframeOptions {
  id?: string;
  name?: string;
  icon?: string;
  basePath?: string;
  port?: number;
  auth?: boolean;
  exampleSource?: boolean;
}
export interface DataSourceEntry {
  id: string;
  title: string;
  description?: string;
  icon?: string;
  data: unknown | (() => unknown | Promise<unknown>);
  static?: boolean;
  writable?: boolean;
  subscribe?: (_: () => void) => (() => void) | void;
  queries?: Query[];
}
export interface DataSourceHandle {
  notifyChanged: () => void;
  unregister: () => void;
}
export interface DataSourcesService {
  register: (_: DataSourceEntry) => DataSourceHandle;
  unregister: (_: string) => void;
  list: () => DataSourceMeta[];
  get: (_: string) => DataSourceEntry | undefined;
  onChanged: (_: () => void) => () => void;
  onDataChanged: (_: (_: string) => void) => () => void;
}
// #endregion

// #region Functions
export declare function createDataInspectorDevframe(_?: DataInspectorDevframeOptions): DevframeDefinition;
export declare function registerDataSource(_: DataSourceEntry): DataSourceHandle;
// #endregion

// #region Variables
export declare const DATA_SOURCES_SERVICE_ID: string;
// #endregion

// #region Default Export
declare function _default(_?: DataInspectorDevframeOptions): DevframeDefinition;
export default _default
// #endregion

// #region Referenced (internal)
interface DataSourceMeta {
  id: string;
  title: string;
  description?: string;
  icon?: string;
  static: boolean;
  writable: boolean;
  queries?: Query[];
}
interface Query extends FilterOptions {
  query: string;
  title?: string;
  description?: string;
}
// #endregion