/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-data-inspector`
 */
// #region Interfaces
export interface DataInspectorDevframeOptions {
  id?: string;
  name?: string;
  icon?: string;
  basePath?: string;
  port?: number;
  auth?: boolean;
}
// #endregion

// #region Functions
export declare function createDataInspectorDevframe(_?: DataInspectorDevframeOptions): DevframeDefinition;
// #endregion

// #region Default Export
declare const _default: DevframeDefinition;
export default _default
// #endregion

// #region Other
export { DATA_SOURCES_SERVICE_ID }
export { DataSourceEntry }
export { DataSourcesService }
export { registerDataSource }
// #endregion