/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-data-inspector/inject`
 */
// #region Interfaces
export interface DataInspectorEndpoint {
  websocket: string;
  token?: string;
  close: () => Promise<void>;
}
export interface ExposeDataInspectorOptions {
  sources?: DataSourceEntry[];
  port?: number;
  auth?: boolean;
  token?: string;
  discoveryFile?: boolean;
  silent?: boolean;
  exampleSource?: boolean;
}
export interface InjectDiscovery {
  websocket: string;
  token?: string;
  pid: number;
  startedAt: number;
}
// #endregion

// #region Types
/** @deprecated */
export type AgentDiscovery = InjectDiscovery;
/** @deprecated */
export type DataInspectorAgent = DataInspectorEndpoint;
// #endregion

// #region Functions
export declare function createGlobalThisDataSource(): DataSourceEntry;
export declare function exposeDataInspector(_?: ExposeDataInspectorOptions): Promise<DataInspectorEndpoint>;
// #endregion

// #region Variables
/** @deprecated */
export declare const AGENT_DISCOVERY_FILE: string;
export declare const DISCOVERY_FILE: string;
// #endregion

// #region Referenced (internal)
interface DataSourceEntry {
  id: string;
  title: string;
  description?: string;
  icon?: string;
  data: unknown | (() => unknown | Promise<unknown>);
  static?: boolean;
  writable?: boolean;
  subscribe?: (_: () => void) => (() => void) | void;
  queries?: Query[];
}
// #endregion