/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-data-inspector/inject`
 */
// #region Interfaces
export interface AgentDiscovery {
  websocket: string;
  token?: string;
  pid: number;
  startedAt: number;
}
export interface DataInspectorAgent {
  websocket: string;
  token?: string;
  close: () => Promise<void>;
}
export interface ExposeDataInspectorOptions {
  sources?: DataSourceEntry[];
  port?: number;
  auth?: boolean;
  token?: string;
  discoveryFile?: boolean;
  silent?: boolean;
  exampleSource?: boolean;
}
// #endregion

// #region Functions
export declare function createGlobalThisDataSource(): DataSourceEntry;
export declare function exposeDataInspector(_?: ExposeDataInspectorOptions): Promise<DataInspectorAgent>;
// #endregion

// #region Variables
export declare const AGENT_DISCOVERY_FILE: string;
// #endregion