/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-data-inspector/node`
 */
// #region Interfaces
export interface SetupDataInspectorOptions {
  exampleSource?: boolean;
}
// #endregion

// #region Functions
export declare function createExampleDataSource(_?: DevframeNodeContext): DataSourceEntry;
export declare function setupDataInspector(_: DevframeNodeContext, _?: SetupDataInspectorOptions): void;
// #endregion

// #region Variables
export declare const EXAMPLE_SOURCE_ID: string;
export declare const serverFunctions: readonly [{
  name: "devframes:plugin:data-inspector:sources";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], Promise<DataSourceMeta[]>>>) | undefined;
  handler?: (() => Promise<DataSourceMeta[]>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[], Promise<DataSourceMeta[]>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], Promise<DataSourceMeta[]>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], Promise<DataSourceMeta[]>>> | undefined;
}, {
  name: "devframes:plugin:data-inspector:query";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[sourceId: string, joraQuery: string, options?: ({
    maxDepth?: number;
    maxEntries?: number;
  } & FilterOptions) | undefined], Promise<QueryOutcome>>>) | undefined;
  handler?: ((sourceId: string, joraQuery: string, options?: ({
    maxDepth?: number;
    maxEntries?: number;
  } & FilterOptions) | undefined) => Promise<QueryOutcome>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[sourceId: string, joraQuery: string, options?: ({
    maxDepth?: number;
    maxEntries?: number;
  } & FilterOptions) | undefined], Promise<QueryOutcome>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[sourceId: string, joraQuery: string, options?: ({
    maxDepth?: number;
    maxEntries?: number;
  } & FilterOptions) | undefined], Promise<QueryOutcome>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[sourceId: string, joraQuery: string, options?: ({
    maxDepth?: number;
    maxEntries?: number;
  } & FilterOptions) | undefined], Promise<QueryOutcome>>> | undefined;
}, {
  name: "devframes:plugin:data-inspector:queryPath";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[sourceId: string, joraQuery: string, path: NodePath, options?: ({
    maxDepth?: number;
    maxEntries?: number;
  } & FilterOptions) | undefined], Promise<QueryOutcome>>>) | undefined;
  handler?: ((sourceId: string, joraQuery: string, path: NodePath, options?: ({
    maxDepth?: number;
    maxEntries?: number;
  } & FilterOptions) | undefined) => Promise<QueryOutcome>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[sourceId: string, joraQuery: string, path: NodePath, options?: ({
    maxDepth?: number;
    maxEntries?: number;
  } & FilterOptions) | undefined], Promise<QueryOutcome>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[sourceId: string, joraQuery: string, path: NodePath, options?: ({
    maxDepth?: number;
    maxEntries?: number;
  } & FilterOptions) | undefined], Promise<QueryOutcome>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[sourceId: string, joraQuery: string, path: NodePath, options?: ({
    maxDepth?: number;
    maxEntries?: number;
  } & FilterOptions) | undefined], Promise<QueryOutcome>>> | undefined;
}, {
  name: "devframes:plugin:data-inspector:skeleton";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[sourceId: string, options?: FilterOptions | undefined], Promise<SkeletonOutcome>>>) | undefined;
  handler?: ((sourceId: string, options?: FilterOptions | undefined) => Promise<SkeletonOutcome>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[sourceId: string, options?: FilterOptions | undefined], Promise<SkeletonOutcome>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[sourceId: string, options?: FilterOptions | undefined], Promise<SkeletonOutcome>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[sourceId: string, options?: FilterOptions | undefined], Promise<SkeletonOutcome>>> | undefined;
}, {
  name: "devframes:plugin:data-inspector:suggest";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[sourceId: string, joraQuery: string, pos: number], Promise<SuggestOutcome>>>) | undefined;
  handler?: ((sourceId: string, joraQuery: string, pos: number) => Promise<SuggestOutcome>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[sourceId: string, joraQuery: string, pos: number], Promise<SuggestOutcome>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[sourceId: string, joraQuery: string, pos: number], Promise<SuggestOutcome>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[sourceId: string, joraQuery: string, pos: number], Promise<SuggestOutcome>>> | undefined;
}, {
  name: "devframes:plugin:data-inspector:saved:list";
  type?: "query" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], Promise<SavedQuery[]>>>) | undefined;
  handler?: (() => Promise<SavedQuery[]>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[], Promise<SavedQuery[]>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], Promise<SavedQuery[]>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[], Promise<SavedQuery[]>>> | undefined;
}, {
  name: "devframes:plugin:data-inspector:saved:save";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[input: SaveQueryInput], Promise<SavedQuery>>>) | undefined;
  handler?: ((input: SaveQueryInput) => Promise<SavedQuery>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[input: SaveQueryInput], Promise<SavedQuery>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[input: SaveQueryInput], Promise<SavedQuery>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[input: SaveQueryInput], Promise<SavedQuery>>> | undefined;
}, {
  name: "devframes:plugin:data-inspector:saved:delete";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: import("devframe").RpcFunctionAgentOptions;
  setup?: ((context: import("devframe").DevframeNodeContext) => import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[id: string, scope: SavedQueryScope], Promise<boolean>>>) | undefined;
  handler?: ((id: string, scope: SavedQueryScope) => Promise<boolean>) | undefined;
  dump?: import("devframe/rpc").RpcDump<[id: string, scope: SavedQueryScope], Promise<boolean>, import("devframe").DevframeNodeContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[id: string, scope: SavedQueryScope], Promise<boolean>>>> | undefined;
  __promise?: import("devframe/rpc").Thenable<import("devframe/rpc").RpcFunctionSetupResult<[id: string, scope: SavedQueryScope], Promise<boolean>>> | undefined;
}];
export declare const SOURCES_CHANGED_EVENT: string;
// #endregion