/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-data-inspector/node`
 */
// #region Interfaces
export interface SetupDataInspectorOptions {
  exampleSource?: boolean;
}
// #endregion

// #region Functions
export declare function createExampleDataSource(_?: DevframeNodeContext): DataSourceEntry;
export declare function setupDataInspector(_: DevframeNodeContext, _?: SetupDataInspectorOptions): void;
// #endregion

// #region Variables
export declare const DATA_CHANGED_EVENT: string;
export declare const EXAMPLE_SOURCE_ID: string;
export declare const serverFunctions: readonly [import("devframe/rpc").RpcFunctionDefinitionWithoutSchemas<"devframes:plugin:data-inspector:sources", "query", [], Promise<DataSourceMeta[]>, undefined, undefined, import("devframe").DevframeNodeContext>, import("devframe/rpc").RpcFunctionDefinitionWithoutSchemas<"devframes:plugin:data-inspector:query", "query", [sourceId: string, joraQuery: string, options?: ({
  maxDepth?: number;
  maxEntries?: number;
} & FilterOptions) | undefined], Promise<QueryOutcome>, undefined, undefined, import("devframe").DevframeNodeContext>, import("devframe/rpc").RpcFunctionDefinitionWithoutSchemas<"devframes:plugin:data-inspector:queryPath", "query", [sourceId: string, joraQuery: string, path: NodePath, options?: ({
  maxDepth?: number;
  maxEntries?: number;
} & FilterOptions) | undefined], Promise<QueryOutcome>, undefined, undefined, import("devframe").DevframeNodeContext>, import("devframe/rpc").RpcFunctionDefinitionWithoutSchemas<"devframes:plugin:data-inspector:skeleton", "query", [sourceId: string, options?: FilterOptions | undefined], Promise<SkeletonOutcome>, undefined, undefined, import("devframe").DevframeNodeContext>, import("devframe/rpc").RpcFunctionDefinitionWithoutSchemas<"devframes:plugin:data-inspector:suggest", "query", [sourceId: string, joraQuery: string, pos: number], Promise<SuggestOutcome>, undefined, undefined, import("devframe").DevframeNodeContext>, import("devframe/rpc").RpcFunctionDefinitionWithoutSchemas<"devframes:plugin:data-inspector:saved:list", "query", [], Promise<SavedQuery[]>, undefined, undefined, import("devframe").DevframeNodeContext>, import("devframe/rpc").RpcFunctionDefinitionWithoutSchemas<"devframes:plugin:data-inspector:saved:save", "action", [input: SaveQueryInput], Promise<SavedQuery>, undefined, undefined, import("devframe").DevframeNodeContext>, import("devframe/rpc").RpcFunctionDefinitionWithoutSchemas<"devframes:plugin:data-inspector:saved:delete", "action", [id: string, scope: SavedQueryScope], Promise<boolean>, undefined, undefined, import("devframe").DevframeNodeContext>, import("devframe/rpc").RpcFunctionDefinitionWithoutSchemas<"devframes:plugin:data-inspector:write", "action", [sourceId: string, request: WriteRequest, options?: WriteApplyOptions | undefined], Promise<WriteOutcome>, undefined, undefined, import("devframe").DevframeNodeContext>];
export declare const SOURCES_CHANGED_EVENT: string;
// #endregion

// #region Referenced (internal)
interface DataSourceEntry {
  id: string;
  title: string;
  description?: string;
  icon?: string;
  data: unknown | (() => unknown | Promise<unknown>);
  static?: boolean;
  writable?: boolean;
  subscribe?: (_: () => void) => (() => void) | void;
  queries?: Query[];
}
interface DataSourceMeta {
  id: string;
  title: string;
  description?: string;
  icon?: string;
  static: boolean;
  writable: boolean;
  queries?: Query[];
}
interface FilterOptions {
  excludeFunctions?: boolean;
  excludeUnderscoreProps?: boolean;
  excludeDollarProps?: boolean;
}
type NodePath = PathSegment[];
type QueryOutcome = {
  ok: true;
  result: unknown;
  stats: QueryStats;
} | {
  ok: false;
  error: {
    name: string;
    message: string;
  };
};
interface SavedQuery extends Query {
  id: string;
  scope: SavedQueryScope;
  updatedAt: number;
}
type SavedQueryScope = 'workspace' | 'project';
interface SaveQueryInput extends Query {
  id?: string;
  scope: SavedQueryScope;
}
type SkeletonOutcome = {
  ok: true;
  skeleton: unknown;
  nodes: number;
  ms: number;
} | {
  ok: false;
  error: {
    name: string;
    message: string;
  };
};
interface SuggestOutcome {
  ok: boolean;
  suggestions: SuggestItem[];
  statMs: number;
  error?: string;
}
interface WriteApplyOptions {
  excludeFunctions?: boolean;
}
type WriteOutcome = {
  ok: true;
} | {
  ok: false;
  error: {
    name: string;
    message: string;
  };
};
type WriteRequest = {
  op: 'set';
  path: NodePath;
  value: WriteValue;
} | {
  op: 'delete';
  path: NodePath;
} | {
  op: 'add';
  path: NodePath;
  key?: WriteValue;
  value: WriteValue;
} | {
  op: 'rename';
  path: NodePath;
  key: WriteValue;
};
// #endregion