/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-data-inspector/registry`
 */
// #region Interfaces
export interface DataSourceEntry {
  id: string;
  title: string;
  description?: string;
  icon?: string;
  data: unknown | (() => unknown | Promise<unknown>);
  static?: boolean;
  queries?: Query[];
}
export interface DataSourcesService {
  register: (_: DataSourceEntry) => () => void;
  unregister: (_: string) => void;
  list: () => DataSourceMeta[];
  get: (_: string) => DataSourceEntry | undefined;
  onChanged: (_: () => void) => () => void;
}
// #endregion

// #region Functions
export declare function createDataSourcesService(): DataSourcesService;
export declare function getDataSource(_: string): DataSourceEntry | undefined;
export declare function listDataSources(): DataSourceMeta[];
export declare function onDataSourcesChanged(_: () => void): () => void;
export declare function registerDataSource(_: DataSourceEntry): () => void;
export declare function resetDataSources(): void;
export declare function resolveSourceData(_: DataSourceEntry): Promise<unknown>;
export declare function unregisterDataSource(_: string): void;
// #endregion

// #region Variables
export declare const DATA_SOURCES_SERVICE_ID: string;
// #endregion