/**
 * Generated by tsnapi — public API snapshot of `@devframes/plugin-data-inspector/vite`
 */
// #region Functions
export declare function dataInspectorVitePlugin(_?: DevframeViteOptions): DevframeVitePlugin;
// #endregion

// #region Other
export { DevframeViteOptions }
// #endregion