/**
 * Generated by tsnapi — public API snapshot of `devframe/node/auth`
 */
// #region Functions
export declare function buildAuthPairingUrl(_: string, _?: string): string;
export declare function exchangeTempAuthCode(_: string, _: DevframeNodeRpcSession, _: {
  ua: string;
  origin: string;
}, _: SharedState<InternalAnonymousAuthStorage>): string | null;
export declare function getTempAuthToken(): string;
export declare function refreshTempAuthToken(): string;
export declare function revokeActiveConnectionsForToken(_: DevframeNodeContext, _: string): Promise<void>;
export declare function revokeAuthToken(_: DevframeNodeContext, _: SharedState<InternalAnonymousAuthStorage>, _: string): Promise<void>;
export declare function verifyAuthToken(_: string, _: DevframeNodeRpcSession, _: SharedState<InternalAnonymousAuthStorage>): boolean;
// #endregion