/**
 * Generated by tsnapi — public API snapshot of `devframe/node/hub-internals`
 */
// #region Other
export { DevframeInternalContext }
export { getInternalContext }
export { InternalAnonymousAuthStorage }
export { internalContextMap }
export { normalizeBasePath }
export { RemoteTokenRecord }
export { resolveBasePath }
// #endregion