/**
 * Generated by tsnapi — public API snapshot of `devframe/helpers/vite`
 */
// #region Interfaces
export interface DevframeViteDevServerLike {
  middlewares: {
    use: ((_: string, _: (_: IncomingMessage, _: ServerResponse, _?: (_?: unknown) => void) => void) => void) & ((_: (_: IncomingMessage, _: ServerResponse, _?: (_?: unknown) => void) => void) => void);
  };
  httpServer?: Server | null;
}
export interface DevframeVitePlugin {
  name: string;
  apply: 'serve';
  configureServer: (_: DevframeViteDevServerLike) => void | Promise<void>;
  closeBundle?: () => void | Promise<void>;
}
export interface ViteDevBridgeOptions {
  base?: string;
  devMiddleware?: boolean | {
    port?: number;
    host?: string;
    flags?: Record<string, unknown>;
  };
  auth?: boolean | DevframeAuthHandler;
  mcp?: boolean | McpRouteOptions;
}
// #endregion

// #region Functions
export declare function viteDevBridge(_: DevframeDefinition, _?: ViteDevBridgeOptions): DevframeVitePlugin;
// #endregion