/**
 * Generated by tsnapi — public API snapshot of `@devframes/hub/build`
 */
// #region Interfaces
export interface BuildHubOptions {
  outDir: string;
  base?: string;
  devframes?: DevframesInput;
  services?: DevframeServiceInput[];
  rpcDeclarations?: CreateHubContextOptions['builtinRpcDeclarations'];
  configure?: (_: DevframeHubContext) => void | Promise<void>;
  ui?: DevframeHubUi;
  renderers?: readonly DockRendererRegistration[];
  name?: string;
  version?: string;
  cwd?: string;
  getStorageDir?: (_: DevframeStorageScope) => string;
  pretty?: boolean;
}
// #endregion

// #region Functions
export declare function buildHub(_: BuildHubOptions): Promise<void>;
// #endregion