/**
 * Generated by tsnapi — public API snapshot of `@devframes/hub/client`
 */
// #region Interfaces
export interface CommandsContext {
  readonly commands: DevframeCommandEntry[];
  readonly paletteCommands: DevframeCommandEntry[];
  register: (_: DevframeClientCommand | DevframeClientCommand[]) => () => void;
  execute: (_: string, ..._: any[]) => Promise<unknown>;
  getKeybindings: (_: string) => DevframeCommandKeybinding[];
  settings: SharedState<DevframeDocksUserSettings>;
  paletteOpen: boolean;
}
export interface DevframeClientHost {
  context: DevframeClientContext;
  dispose: () => void;
}
export interface DevframeClientHostOptions {
  rpc?: DevframeRpcClient;
  connect?: DevframeRpcClientOptions;
  clientType?: DockClientType;
  loadClientScripts?: boolean;
}
export interface DockClientScriptContext extends DocksContext {
  current: DockEntryState;
  messages: DevframeMessagesClient;
}
export interface DockEntryState {
  entryMeta: DevframeDockEntry;
  readonly isActive: boolean;
  domElements: {
    iframe?: HTMLIFrameElement | null;
    panel?: HTMLDivElement | null;
  };
  events: EventEmitter<DockEntryStateEvents>;
}
export interface DockEntryStateEvents {
  'entry:activated': () => void;
  'entry:deactivated': () => void;
  'entry:updated': (_: DevframeDockUserEntry) => void;
  'dom:panel:mounted': (_: HTMLDivElement) => void;
  'dom:iframe:mounted': (_: HTMLIFrameElement) => void;
}
export interface DockPanelStorage {
  mode: 'float' | 'edge';
  width: number;
  height: number;
  top: number;
  left: number;
  position: 'left' | 'right' | 'bottom' | 'top';
  open: boolean;
  inactiveTimeout: number;
}
export interface DocksContext extends DevframeRpcContext {
  readonly clientType: 'embedded' | 'standalone';
  readonly panel: DocksPanelContext;
  readonly docks: DocksEntriesContext;
  readonly commands: CommandsContext;
  readonly when: WhenClauseContext;
}
export interface DocksEntriesContext {
  selectedId: string | null;
  readonly selected: DevframeDockEntry | null;
  entries: DevframeDockEntry[];
  entryToStateMap: Map<string, DockEntryState>;
  groupedEntries: DevframeDockEntriesGrouped;
  settings: SharedState<DevframeDocksUserSettings>;
  getStateById: (_: string) => DockEntryState | undefined;
  switchEntry: (_?: string | null) => Promise<boolean>;
  toggleEntry: (_: string) => Promise<boolean>;
}
export interface DocksPanelContext {
  store: DockPanelStorage;
  isDragging: boolean;
  isResizing: boolean;
  readonly isVertical: boolean;
}
export interface MessagesClientOptions {
  defaults?: Partial<DevframeMessageEntryInput>;
}
export interface WhenClauseContext {
  readonly context: WhenContext;
}
// #endregion

// #region Types
export type ConnectRemoteDevframeOptions = Omit<DevframeRpcClientOptions, 'connectionMeta' | 'authToken'>;
export type DevframeClientContext = DocksContext;
export type DockClientType = 'embedded' | 'standalone';
// #endregion

// #region Functions
export declare function connectRemoteDevframe(_?: ConnectRemoteDevframeOptions): Promise<DevframeRpcClient>;
export declare function createDevframeClientHost(_?: DevframeClientHostOptions): Promise<DevframeClientHost>;
export declare function createMessagesClient(_: DevframeRpcClient, _?: MessagesClientOptions): DevframeMessagesClient;
export declare function getDevframeClientContext(): DevframeClientContext | undefined;
export declare function parseRemoteConnection(_?: string): RemoteConnectionInfo | null;
export declare function setDevframeClientContext(_: DevframeClientContext | undefined): void;
// #endregion

// #region Variables
export declare const CLIENT_CONTEXT_KEY: string;
// #endregion

// #region Re-exports
export * from "devframe/client";
// #endregion

// #region Other
export { DevframeClientRpcHost }
export { RpcClientEvents }
// #endregion