/**
 * Generated by tsnapi — public API snapshot of `@devframes/hub`
 */
// #region Functions
export declare function defineCommand<const W extends string = ''>(_: Omit<DevframeServerCommandInput, 'when'> & {
  when?: WhenExpression<WhenContext, W>;
}): DevframeServerCommandInput;
export declare function defineDockEntry<const T extends DevframeDockUserEntry, const W extends string = ''>(_: Omit<T, 'when'> & {
  when?: WhenExpression<WhenContext, W>;
}): T;
/** @deprecated */
export declare function defineJsonRenderSpec(_: JsonRenderSpec): JsonRenderSpec;
// #endregion

// #region Variables
export declare const defineHubRpcFunction: <NAME extends string, TYPE extends import("devframe/rpc").RpcFunctionType, ARGS extends any[], RETURN = void, const AS extends import("devframe/rpc").RpcArgsSchema | undefined = undefined, const RS extends import("devframe/rpc").RpcReturnSchema | undefined = undefined>(definition: import("devframe/rpc").RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, DevframeHubContext>) => import("devframe/rpc").RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, DevframeHubContext>;
// #endregion

// #region Other
export { ClientScriptEntry }
export { ConnectionMeta }
export { CreateHubContextOptions }
export { DEFAULT_CATEGORIES_ORDER }
export { DevframeCapabilities }
export { DevframeChildProcessExecuteOptions }
export { DevframeChildProcessOutput }
export { DevframeChildProcessResult }
export { DevframeChildProcessTerminalSession }
export { DevframeClientCommand }
export { DevframeCommandBase }
export { DevframeCommandEntry }
export { DevframeCommandHandle }
export { DevframeCommandKeybinding }
export { DevframeCommandShortcutOverrides }
export { DevframeCommandsHost }
export { DevframeCommandsHostEvents }
export { DevframeDiagnosticsDefinition }
export { DevframeDiagnosticsHost }
export { DevframeDiagnosticsLogger }
export { DevframeDockActivation }
export { DevframeDockEntriesGrouped }
export { DevframeDockEntry }
export { DevframeDockEntryBase }
export { DevframeDockEntryCategory }
export { DevframeDockEntryIcon }
export { DevframeDockEntryRegistry }
export { DevframeDocksActiveState }
export { DevframeDocksHost }
export { DevframeDocksUserSettings }
export { DevframeDockUserEntry }
export { DevframeHost }
export { DevframeHubContext }
export { DevframeMessageAction }
export { DevframeMessageActivateAction }
export { DevframeMessageElementPosition }
export { DevframeMessageEntry }
export { DevframeMessageEntryFrom }
export { DevframeMessageEntryInput }
export { DevframeMessageFilePosition }
export { DevframeMessageHandle }
export { DevframeMessageLevel }
export { DevframeMessagesClient }
export { DevframeMessageShortcutInput }
export { DevframeMessagesHost }
export { DevframeMessagesLevelShortcuts }
export { DevframeMessagesListDelta }
export { DevframeNodeRpcSession }
export { DevframePtyExecuteOptions }
export { DevframePtyTerminalSession }
export { DevframeRpcClientFunctions }
export { DevframeRpcServerFunctions }
export { DevframeRpcSharedStates }
export { DevframeServerCommandEntry }
export { DevframeServerCommandInput }
export { DevframeTerminalSession }
export { DevframeTerminalSessionBase }
export { DevframeTerminalsHost }
export { DevframeTerminalStatus }
export { DevframeViewAction }
export { DevframeViewBuiltin }
export { DevframeViewCustomRender }
export { DevframeViewGroup }
export { DevframeViewHost }
export { DevframeViewIframe }
export { DevframeViewJsonRender }
export { DevframeViewLauncher }
export { DevframeViewLauncherStatus }
export { EntriesToObject }
export { EventEmitter }
export { EventsMap }
export { EventUnsubscribe }
export { FrameSubTabsConfig }
export { JsonRenderElement }
export { JsonRenderer }
export { JsonRenderSpec }
export { NavTarget }
export { PartialWithoutId }
export { RemoteConnectionInfo }
export { RemoteDockOptions }
export { RpcBroadcastOptions }
export { RpcDefinitionsFilter }
export { RpcDefinitionsToFunctions }
export { RpcFunctionsHost }
export { RpcSharedStateGetOptions }
export { RpcSharedStateHost }
export { RpcStreamingChannel }
export { RpcStreamingChannelOptions }
export { RpcStreamingHost }
export { Thenable }
// #endregion