/**
 * Generated by tsnapi — public API snapshot of `@devframes/hub`
 */
// #region Functions
export declare function defineCommand<const W extends string = ''>(_: Omit<DevToolsServerCommandInput, 'when'> & {
  when?: WhenExpression<WhenContext, W>;
}): DevToolsServerCommandInput;
export declare function defineDockEntry<const T extends DevToolsDockUserEntry, const W extends string = ''>(_: Omit<T, 'when'> & {
  when?: WhenExpression<WhenContext, W>;
}): T;
export declare function defineJsonRenderSpec(_: JsonRenderSpec): JsonRenderSpec;
// #endregion

// #region Variables
export declare const defineRpcFunction: <NAME extends string, TYPE extends _$devframe_rpc0.RpcFunctionType, ARGS extends any[], RETURN = void, const AS extends _$devframe_rpc0.RpcArgsSchema | undefined = undefined, const RS extends _$devframe_rpc0.RpcReturnSchema | undefined = undefined>(definition: _$devframe_rpc0.RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, HubNodeContext>) => _$devframe_rpc0.RpcFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS, HubNodeContext>;
// #endregion

// #region Other
export { ClientScriptEntry }
export { ConnectionMeta }
export { CreateHubContextOptions }
export { DevToolsCapabilities }
export { DevToolsChildProcessExecuteOptions }
export { DevToolsChildProcessTerminalSession }
export { DevToolsClientCommand }
export { DevToolsCommandBase }
export { DevToolsCommandEntry }
export { DevToolsCommandHandle }
export { DevToolsCommandKeybinding }
export { DevToolsCommandShortcutOverrides }
export { DevToolsCommandsHost }
export { DevToolsCommandsHostEvents }
export { DevToolsDiagnosticsDefinition }
export { DevToolsDiagnosticsHost }
export { DevToolsDiagnosticsLogger }
export { DevToolsDockEntriesGrouped }
export { DevToolsDockEntry }
export { DevToolsDockEntryBase }
export { DevToolsDockEntryCategory }
export { DevToolsDockEntryIcon }
export { DevToolsDockHost }
export { DevToolsDocksUserSettings }
export { DevToolsDockUserEntry }
export { DevToolsHost }
export { DevToolsMessageElementPosition }
export { DevToolsMessageEntry }
export { DevToolsMessageEntryFrom }
export { DevToolsMessageEntryInput }
export { DevToolsMessageFilePosition }
export { DevToolsMessageHandle }
export { DevToolsMessageLevel }
export { DevToolsMessagesClient }
export { DevToolsMessagesHost }
export { DevToolsNodeRpcSession }
export { DevToolsRpcClientFunctions }
export { DevToolsRpcServerFunctions }
export { DevToolsRpcSharedStates }
export { DevToolsServerCommandEntry }
export { DevToolsServerCommandInput }
export { DevToolsTerminalHost }
export { DevToolsTerminalSession }
export { DevToolsTerminalSessionBase }
export { DevToolsTerminalStatus }
export { DevToolsViewAction }
export { DevToolsViewBuiltin }
export { DevToolsViewCustomRender }
export { DevToolsViewHost }
export { DevToolsViewIframe }
export { DevToolsViewJsonRender }
export { DevToolsViewLauncher }
export { DevToolsViewLauncherStatus }
export { EntriesToObject }
export { EventEmitter }
export { EventsMap }
export { EventUnsubscribe }
export { HubNodeContext }
export { JsonRenderElement }
export { JsonRenderer }
export { JsonRenderSpec }
export { PartialWithoutId }
export { RemoteConnectionInfo }
export { RemoteDockOptions }
export { RpcBroadcastOptions }
export { RpcDefinitionsFilter }
export { RpcDefinitionsToFunctions }
export { RpcFunctionsHost }
export { RpcSharedStateGetOptions }
export { RpcSharedStateHost }
export { RpcStreamingChannel }
export { RpcStreamingChannelOptions }
export { RpcStreamingHost }
export { Thenable }
// #endregion