/**
 * Generated by tsnapi — public API snapshot of `@devframes/hub/initiate`
 */
// #region Interfaces
export interface DevframeHubUi {
  viewer?: {
    distDir: string;
  };
  embedded?: {
    entry: string;
  };
  assets?: Record<string, () => string | Uint8Array>;
  setup?: (_: DevframeHubContext) => void | Promise<void>;
}
export interface DockRendererRegistration {
  type: string;
  file: string;
  importName?: string;
}
export interface HubDevframeEntry {
  devframe: DevframeDefinition;
  dock?: InstallDevframeOptions['dock'];
}
export interface HubInstance {
  base: string;
  handler: (_: Request) => Promise<Response>;
  nodeMiddleware: (_: IncomingMessage, _: ServerResponse, _?: (_?: unknown) => void) => void;
  attach: (_: Server) => () => void;
  handleUpgrade: (_: IncomingMessage, _: Duplex, _: Buffer) => void;
  ready: Promise<void>;
  context: Promise<DevframeHubContext>;
  connectionMeta: () => ConnectionMeta;
  close: () => Promise<void>;
}
export interface InitHubOptions {
  name?: string;
  version?: string;
  base: string;
  devframes?: DevframesInput;
  rpcDeclarations?: CreateHubContextOptions['builtinRpcDeclarations'];
  context?: DevframeHubContext;
  configure?: (_: DevframeHubContext) => void | Promise<void>;
  ui?: DevframeHubUi;
  renderers?: readonly DockRendererRegistration[];
  server?: Server;
  ws?: DevframeWsOptions | false;
  sse?: boolean | DevframeSseOptions;
  host?: string;
  auth?: boolean | DevframeAuthHandler;
  mcp?: boolean | McpRouteOptions;
  origin?: string | (() => string);
  register?: boolean | Partial<DevframeInstanceRecord>;
  cwd?: string;
  getStorageDir?: (_: DevframeStorageScope) => string;
  allowedOrigins?: readonly string[] | WsOriginRegistry | false;
  destroyUnmatchedUpgrades?: boolean;
}
// #endregion

// #region Types
export type DevframesInput = Array<DevframeDefinition | HubDevframeEntry | Thenable<Arrayable<DevframeDefinition | HubDevframeEntry | null | undefined>> | (() => Thenable<Arrayable<DevframeDefinition | HubDevframeEntry | null | undefined>>)>;
// #endregion

// #region Functions
export declare function initHub(_: InitHubOptions): HubInstance;
// #endregion

// #region Other
export { DEVFRAMES_HUB_BASE }
// #endregion