/**
 * Generated by tsnapi — public API snapshot of `@devframes/hub/node`
 */
// #region Interfaces
export interface MountDevframeOptions {
  base?: string;
  dock?: Partial<Omit<DevframeViewIframe, 'id' | 'type' | 'url'>>;
}
// #endregion

// #region Classes
export declare class DevframeCommandsHost implements DevframeCommandsHost$1 {
  readonly context: HubNodeContext;
  readonly commands: DevframeCommandsHost$1['commands'];
  readonly events: DevframeCommandsHost$1['events'];
  constructor(_: HubNodeContext);
  register(_: DevframeServerCommandInput): DevframeCommandHandle;
  unregister(_: string): boolean;
  execute(_: string, ..._: any[]): Promise<unknown>;
  list(): DevframeServerCommandEntry[];
  private findCommand;
  private toSerializable;
}
export declare class DevframeDockHost implements DevframeDockHost$1 {
  readonly context: HubNodeContext;
  readonly views: DevframeDockHost$1['views'];
  readonly events: DevframeDockHost$1['events'];
  userSettings: SharedState<DevframeDocksUserSettings>;
  private readonly remoteDocks;
  constructor(_: HubNodeContext);
  init(): Promise<void>;
  values({
    includeBuiltin
  }?: {
    includeBuiltin?: boolean;
  }): DevframeDockEntry[];
  private projectView;
  private resolveDevServerOrigin;
  register<T extends DevframeDockUserEntry>(_: T, _?: boolean): {
    update: (_: Partial<T>) => void;
  };
  update(_: DevframeDockUserEntry): void;
  private prepareRemoteRegistration;
}
export declare class DevframeMessagesHost implements DevframeMessagesHost$1 {
  readonly context: HubNodeContext;
  readonly entries: DevframeMessagesHost$1['entries'];
  readonly events: DevframeMessagesHost$1['events'];
  readonly lastModified: Map<string, number>;
  readonly removals: Array<{
    id: string;
    time: number;
  }>;
  private _autoDeleteTimers;
  private _clock;
  private _tick;
  constructor(_: HubNodeContext);
  add(_: DevframeMessageEntryInput): Promise<DevframeMessageHandle>;
  update(_: string, _: Partial<DevframeMessageEntryInput>): Promise<DevframeMessageEntry | undefined>;
  remove(_: string): Promise<void>;
  clear(): Promise<void>;
  private _createHandle;
}
export declare class DevframeTerminalHost implements DevframeTerminalHost$1 {
  readonly context: HubNodeContext;
  readonly sessions: DevframeTerminalHost$1['sessions'];
  readonly events: DevframeTerminalHost$1['events'];
  private _boundStreams;
  private _channel?;
  constructor(_: HubNodeContext);
  private getStreamingChannel;
  register(_: DevframeTerminalSession): DevframeTerminalSession;
  update(_: PartialWithoutId<DevframeTerminalSession>): void;
  remove(_: DevframeTerminalSession): void;
  private bindStream;
  startChildProcess(_: DevframeChildProcessExecuteOptions, _: Omit<DevframeTerminalSessionBase, 'status'>): Promise<DevframeChildProcessTerminalSession>;
}
// #endregion

// #region Functions
export declare function createSimpleClientScript(_: string | ((_: any) => void)): ClientScriptEntry;
export declare function mountDevframe(_: HubNodeContext, _: DevframeDefinition, _?: MountDevframeOptions): Promise<void>;
export declare function registerHubBuiltins(_: HubNodeContext): void;
// #endregion

// #region Variables
export declare const builtinHubRpcDeclarations: readonly RpcFunctionDefinitionAny[];
export declare const hubCommandsExecute: {
  name: "hub:commands:execute";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: HubNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[id: string, ...args: any[]], Promise<unknown>>>) | undefined;
  handler?: ((id: string, ...args: any[]) => Promise<unknown>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[id: string, ...args: any[]], Promise<unknown>, HubNodeContext> | undefined;
  snapshot?: boolean;
  __resolved?: _$devframe_rpc0.RpcFunctionSetupResult<[id: string, ...args: any[]], Promise<unknown>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[id: string, ...args: any[]], Promise<unknown>>> | undefined;
};
// #endregion

// #region Other
export { createHubContext }
export { CreateHubContextOptions }
export { HubHostCapabilities }
export { HubNodeContext }
// #endregion