/**
 * Generated by tsnapi — public API snapshot of `@devframes/hub/node`
 */
// #region Interfaces
export interface MountDevframeOptions {
  base?: string;
  dock?: Partial<Omit<DevframeViewIframe, 'id' | 'type' | 'url'>>;
}
// #endregion

// #region Classes
export declare class DevframeCommandsHost implements DevframeCommandsHost$1 {
  readonly context: DevframeHubContext;
  readonly commands: DevframeCommandsHost$1['commands'];
  readonly events: DevframeCommandsHost$1['events'];
  constructor(_: DevframeHubContext);
  register(_: DevframeServerCommandInput): DevframeCommandHandle;
  unregister(_: string): boolean;
  execute(_: string, ..._: any[]): Promise<unknown>;
  list(): DevframeServerCommandEntry[];
  private findCommand;
  private toSerializable;
}
export declare class DevframeDocksHost implements DevframeDocksHost$1 {
  readonly context: DevframeHubContext;
  readonly views: DevframeDocksHost$1['views'];
  readonly events: DevframeDocksHost$1['events'];
  userSettings: SharedState<DevframeDocksUserSettings>;
  private readonly remoteDocks;
  constructor(_: DevframeHubContext);
  init(): Promise<void>;
  values({
    includeBuiltin
  }?: {
    includeBuiltin?: boolean;
  }): DevframeDockEntry[];
  private projectView;
  private resolveDevServerOrigin;
  register<T extends DevframeDockUserEntry>(_: T, _?: boolean): {
    update: (_: Partial<T>) => void;
  };
  update(_: DevframeDockUserEntry): void;
  private validateGroupMembership;
  private prepareRemoteRegistration;
}
export declare class DevframeMessagesHost implements DevframeMessagesHost$1 {
  readonly context: DevframeHubContext;
  readonly entries: DevframeMessagesHost$1['entries'];
  readonly events: DevframeMessagesHost$1['events'];
  readonly lastModified: Map<string, number>;
  readonly removals: Array<{
    id: string;
    time: number;
  }>;
  private _autoDeleteTimers;
  private _clock;
  private _tick;
  constructor(_: DevframeHubContext);
  add(_: DevframeMessageEntryInput): Promise<DevframeMessageHandle>;
  update(_: string, _: Partial<DevframeMessageEntryInput>): Promise<DevframeMessageEntry | undefined>;
  remove(_: string): Promise<void>;
  clear(): Promise<void>;
  private _createHandle;
}
export declare class DevframeTerminalsHost implements DevframeTerminalsHost$1 {
  readonly context: DevframeHubContext;
  readonly sessions: DevframeTerminalsHost$1['sessions'];
  readonly events: DevframeTerminalsHost$1['events'];
  private _boundStreams;
  private _channel?;
  constructor(_: DevframeHubContext);
  private getStreamingChannel;
  register(_: DevframeTerminalSession): DevframeTerminalSession;
  update(_: PartialWithoutId<DevframeTerminalSession>): void;
  remove(_: DevframeTerminalSession): void;
  private bindStream;
  startChildProcess(_: DevframeChildProcessExecuteOptions, _: Omit<DevframeTerminalSessionBase, 'status'>): Promise<DevframeChildProcessTerminalSession>;
}
// #endregion

// #region Functions
export declare function createSimpleClientScript(_: string | ((_: any) => void)): ClientScriptEntry;
export declare function mountDevframe(_: DevframeHubContext, _: DevframeDefinition, _?: MountDevframeOptions): Promise<void>;
// #endregion

// #region Variables
export declare const builtinHubRpcDeclarations: readonly RpcFunctionDefinitionAny[];
export declare const hubCommandsExecute: {
  name: "hub:commands:execute";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: DevframeHubContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[id: string, ...args: any[]], Promise<unknown>>>) | undefined;
  handler?: ((id: string, ...args: any[]) => Promise<unknown>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[id: string, ...args: any[]], Promise<unknown>, DevframeHubContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[id: string, ...args: any[]], Promise<unknown>>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[id: string, ...args: any[]], Promise<unknown>>> | undefined;
};
export declare const hubMessagesAdd: {
  name: "hub:messages:add";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: DevframeHubContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[input: DevframeMessageEntryInput], Promise<DevframeMessageEntry>>>) | undefined;
  handler?: ((input: DevframeMessageEntryInput) => Promise<DevframeMessageEntry>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[input: DevframeMessageEntryInput], Promise<DevframeMessageEntry>, DevframeHubContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[input: DevframeMessageEntryInput], Promise<DevframeMessageEntry>>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[input: DevframeMessageEntryInput], Promise<DevframeMessageEntry>>> | undefined;
};
export declare const hubMessagesClear: {
  name: "hub:messages:clear";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: DevframeHubContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<void>>>) | undefined;
  handler?: (() => Promise<void>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[], Promise<void>, DevframeHubContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<void>>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[], Promise<void>>> | undefined;
};
export declare const hubMessagesRemove: {
  name: "hub:messages:remove";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: DevframeHubContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[id: string], Promise<void>>>) | undefined;
  handler?: ((id: string) => Promise<void>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[id: string], Promise<void>, DevframeHubContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[id: string], Promise<void>>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[id: string], Promise<void>>> | undefined;
};
export declare const hubMessagesUpdate: {
  name: "hub:messages:update";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: DevframeHubContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[id: string, patch: Partial<DevframeMessageEntryInput>], Promise<DevframeMessageEntry | undefined>>>) | undefined;
  handler?: ((id: string, patch: Partial<DevframeMessageEntryInput>) => Promise<DevframeMessageEntry | undefined>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[id: string, patch: Partial<DevframeMessageEntryInput>], Promise<DevframeMessageEntry | undefined>, DevframeHubContext> | undefined;
  snapshot?: boolean;
  __cache?: WeakMap<object, _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[id: string, patch: Partial<DevframeMessageEntryInput>], Promise<DevframeMessageEntry | undefined>>>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[id: string, patch: Partial<DevframeMessageEntryInput>], Promise<DevframeMessageEntry | undefined>>> | undefined;
};
// #endregion

// #region Other
export { createHubContext }
export { CreateHubContextOptions }
export { DevframeHubContext }
// #endregion