/**
 * Generated by tsnapi — public API snapshot of `@devframes/hub/node`
 */
// #region Interfaces
export interface MountDevframeOptions {
  base?: string;
  dock?: Partial<Omit<DevToolsViewIframe, 'id' | 'type' | 'url'>>;
}
// #endregion

// #region Classes
export declare class DevToolsCommandsHost implements DevToolsCommandsHost$1 {
  readonly context: HubNodeContext;
  readonly commands: DevToolsCommandsHost$1['commands'];
  readonly events: DevToolsCommandsHost$1['events'];
  constructor(_: HubNodeContext);
  register(_: DevToolsServerCommandInput): DevToolsCommandHandle;
  unregister(_: string): boolean;
  execute(_: string, ..._: any[]): Promise<unknown>;
  list(): DevToolsServerCommandEntry[];
  private findCommand;
  private toSerializable;
}
export declare class DevToolsDockHost implements DevToolsDockHost$1 {
  readonly context: HubNodeContext;
  readonly views: DevToolsDockHost$1['views'];
  readonly events: DevToolsDockHost$1['events'];
  userSettings: SharedState<DevToolsDocksUserSettings>;
  private readonly remoteDocks;
  constructor(_: HubNodeContext);
  init(): Promise<void>;
  values({
    includeBuiltin
  }?: {
    includeBuiltin?: boolean;
  }): DevToolsDockEntry[];
  private projectView;
  private resolveDevServerOrigin;
  register<T extends DevToolsDockUserEntry>(_: T, _?: boolean): {
    update: (_: Partial<T>) => void;
  };
  update(_: DevToolsDockUserEntry): void;
  private prepareRemoteRegistration;
}
export declare class DevToolsMessagesHost implements DevToolsMessagesHost$1 {
  readonly context: HubNodeContext;
  readonly entries: DevToolsMessagesHost$1['entries'];
  readonly events: DevToolsMessagesHost$1['events'];
  readonly lastModified: Map<string, number>;
  readonly removals: Array<{
    id: string;
    time: number;
  }>;
  private _autoDeleteTimers;
  private _clock;
  private _tick;
  constructor(_: HubNodeContext);
  add(_: DevToolsMessageEntryInput): Promise<DevToolsMessageHandle>;
  update(_: string, _: Partial<DevToolsMessageEntryInput>): Promise<DevToolsMessageEntry | undefined>;
  remove(_: string): Promise<void>;
  clear(): Promise<void>;
  private _createHandle;
}
export declare class DevToolsTerminalHost implements DevToolsTerminalHost$1 {
  readonly context: HubNodeContext;
  readonly sessions: DevToolsTerminalHost$1['sessions'];
  readonly events: DevToolsTerminalHost$1['events'];
  private _boundStreams;
  private _channel?;
  constructor(_: HubNodeContext);
  private getStreamingChannel;
  register(_: DevToolsTerminalSession): DevToolsTerminalSession;
  update(_: PartialWithoutId<DevToolsTerminalSession>): void;
  remove(_: DevToolsTerminalSession): void;
  private bindStream;
  startChildProcess(_: DevToolsChildProcessExecuteOptions, _: Omit<DevToolsTerminalSessionBase, 'status'>): Promise<DevToolsChildProcessTerminalSession>;
}
// #endregion

// #region Functions
export declare function createSimpleClientScript(_: string | ((_: any) => void)): ClientScriptEntry;
export declare function mountDevframe(_: HubNodeContext, _: DevframeDefinition, _?: MountDevframeOptions): Promise<void>;
export declare function registerHubBuiltins(_: HubNodeContext): void;
// #endregion

// #region Variables
export declare const builtinHubRpcDeclarations: readonly RpcFunctionDefinitionAny[];
export declare const hubCommandsExecute: {
  name: "hub:commands:execute";
  type?: "action" | undefined;
  cacheable?: boolean;
  args?: undefined;
  returns?: undefined;
  jsonSerializable?: boolean;
  agent?: _$devframe.RpcFunctionAgentOptions;
  setup?: ((context: HubNodeContext) => _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[id: string, ...args: any[]], Promise<unknown>>>) | undefined;
  handler?: ((id: string, ...args: any[]) => Promise<unknown>) | undefined;
  dump?: _$devframe_rpc0.RpcDump<[id: string, ...args: any[]], Promise<unknown>, HubNodeContext> | undefined;
  snapshot?: boolean;
  __resolved?: _$devframe_rpc0.RpcFunctionSetupResult<[id: string, ...args: any[]], Promise<unknown>> | undefined;
  __promise?: _$devframe_rpc0.Thenable<_$devframe_rpc0.RpcFunctionSetupResult<[id: string, ...args: any[]], Promise<unknown>>> | undefined;
};
// #endregion

// #region Other
export { createHubContext }
export { CreateHubContextOptions }
export { HubHostCapabilities }
export { HubNodeContext }
// #endregion