/**
 * Generated by tsnapi — public API snapshot of `@devframes/next/hub/client`
 */
// #region Interfaces
export interface UseDevframeHubClientOptions extends DevframeClientHostOptions$1 {
  base?: string;
}
// #endregion

// #region Functions
export declare function useDevframeHubClient(_?: UseDevframeHubClientOptions): DevframeClientHost$1 | null;
// #endregion

// #region Other
export { DevframeClientHost }
export { DevframeClientHostOptions }
// #endregion