/**
 * Generated by tsnapi — public API snapshot of `@devframes/next/hub/client`
 */
// #region Interfaces
export interface UseDevframeHubClientOptions extends DevframeClientRuntimeOptions$1 {
  base?: string;
}
// #endregion

// #region Functions
export declare function useDevframeHubClient(_?: UseDevframeHubClientOptions): DevframeClientRuntime$1 | null;
// #endregion

// #region Other
export { DevframeClientHost }
export { DevframeClientHostOptions }
export { DevframeClientRuntime }
export { DevframeClientRuntimeOptions }
// #endregion