/**
 * Generated by tsnapi — public API snapshot of `@devframes/next/client`
 */
// #region Interfaces
export interface RpcProviderProps {
  children: ReactNode;
  baseURL?: string;
  connectionMeta?: ConnectionMeta;
  fallback?: ReactNode;
}
// #endregion

// #region Functions
export declare function RpcProvider({ children, baseURL, connectionMeta, fallback }: RpcProviderProps): ReactNode;
export declare function useRpc(): DevframeRpcClient;
// #endregion