/**
 * Generated by tsnapi — public API snapshot of `@devframes/next/client`
 */
// #region Interfaces
export interface DevframeRpcState {
  rpc: DevframeRpcClient | null;
  status: DevframeConnectionStatus;
  error: Error | null;
}
export interface RpcProviderProps {
  children: ReactNode;
  baseURL?: string;
  connectionMeta?: ConnectionMeta;
}
// #endregion

// #region Functions
export declare function RpcProvider({ children, baseURL, connectionMeta }: RpcProviderProps): ReactNode;
export declare function useRpc(): DevframeRpcClient | null;
export declare function useRpcStatus(): {
  status: DevframeConnectionStatus;
  error: Error | null;
};
// #endregion