/**
 * Generated by tsnapi — public API snapshot of `@devframes/next/hub`
 */
// #region Interfaces
export interface CreateDevframeNextHostOptions {
  resolveOrigin: () => string;
  getStorageDir: (_: DevframeStorageScope) => string;
  connectionMeta?: ConnectionMeta;
}
export interface DevframeNextHost {
  host: DevframeHost;
  fetch: (_: Request) => Promise<Response>;
  setConnectionMeta: (_: ConnectionMeta) => void;
  mountMcp: (_: DevframeNodeContext, _: string, _: DevframeNextHostMcpOptions) => Promise<{
    dispose: () => Promise<void>;
  }>;
}
export interface DevframeNextHostMcpOptions {
  authorization: McpAuthorization;
  serverName?: string;
  serverVersion?: string;
  exposeSharedState?: boolean | ((_: string) => boolean);
  allowedOrigins?: readonly string[] | false;
}
export interface NextDevframeHubHandle {
  base: string;
  handler: (_: Request) => Promise<Response>;
  ready: () => Promise<HubInstance>;
  close: () => Promise<void>;
}
export interface NextDevframeHubOptions {
  base?: string;
  port?: number;
  host?: string;
  cwd?: string;
  devframes?: InitHubOptions['devframes'];
  renderers?: InitHubOptions['renderers'];
  rpcDeclarations?: InitHubOptions['rpcDeclarations'];
  configure?: (_: Parameters<NonNullable<InitHubOptions['configure']>>[0]) => void | Promise<void>;
  ui?: DevframeHubUi | false;
  auth?: InitHubOptions['auth'];
  mcp?: InitHubOptions['mcp'];
  origin?: InitHubOptions['origin'];
  register?: InitHubOptions['register'];
  getStorageDir?: InitHubOptions['getStorageDir'];
  name?: string;
  version?: string;
}
// #endregion

// #region Functions
export declare function createDevframeNextHost(_: CreateDevframeNextHostOptions): DevframeNextHost;
export declare function createNextDevframeHub(_?: NextDevframeHubOptions): Promise<HubInstance>;
export declare function nextDevframeHub(_?: NextDevframeHubOptions): NextDevframeHubHandle;
// #endregion