/**
 * Generated by tsnapi — public API snapshot of `@devframes/next/single`
 */
// #region Interfaces
export interface CreateDevframeNextHandlerOptions {
  base?: string;
  host?: string;
  port?: number;
  flags?: Record<string, unknown>;
  auth?: InitDevframeOptions['auth'];
  allowedOrigins?: InitDevframeOptions['allowedOrigins'];
  resolveOrigin?: () => string;
  getStorageDir?: (_: DevframeStorageScope) => string;
  mcp?: InitDevframeOptions['mcp'];
  key?: string;
}
export interface DevframeNextConfig {
  skipTrailingSlashRedirect?: boolean;
  [key: string]: unknown;
}
export interface DevframeNextHandler {
  fetch: (_: Request) => Promise<Response>;
  ready: Promise<void>;
  close: () => Promise<void>;
}
// #endregion

// #region Functions
export declare function createDevframeNextHandler(_: DevframeDefinition, _?: CreateDevframeNextHandlerOptions): DevframeNextHandler;
export declare function withDevframe<T extends DevframeNextConfig>(_?: T): T;
// #endregion