/**
 * Generated by tsnapi — public API snapshot of `devframe/rpc/transports/ws-deno`
 */
// #region Interfaces
export interface AttachDenoWsTransportOptions {
  allowedOrigins?: readonly string[] | WsOriginRegistry | false;
}
export interface DenoWsTier {
  handleUpgrade: (_: Request, _: unknown) => Promise<Response>;
  close: () => Promise<void>;
}
// #endregion

// #region Functions
export declare function attachDenoWsTransport(_: ContextRpcServer, _?: AttachDenoWsTransportOptions): Promise<DenoWsTier>;
// #endregion