/**
 * Generated by tsnapi — public API snapshot of `devframe/rpc/transports/ws-server`
 */
// #region Other
export { attachWsRpcTransport }
export { createWsOriginRegistry }
export { CreateWsOriginRegistryOptions }
export { createWsRpcPeerHooks }
export { DevframeNodeRpcSessionMeta }
export { DevframeRpcConnection }
export { DevframeRpcConnectionRequest }
export { DevframeRpcTransportKind }
export { isAllowedOrigin }
export { isLoopbackHostname }
export { WsOriginRegistry }
export { WsRpcTransport }
export { WsRpcTransportOptions }
// #endregion