/**
 * Generated by tsnapi — public API snapshot of `devframe/rpc/transports/ws-server`
 */
// #region Other
export { attachWsRpcTransport }
export { DevframeNodeRpcSessionMeta }
export { isAllowedOrigin }
export { isLoopbackHostname }
export { WsRpcTransport }
export { WsRpcTransportOptions }
// #endregion