/**
 * Generated by tsnapi — public API snapshot of `devframe/client`
 */
// #region Interfaces
export interface DevframeRpcClient {
  events: EventEmitter<RpcClientEvents>;
  readonly isTrusted: boolean | null;
  readonly connectionMeta: ConnectionMeta;
  ensureTrusted: (_?: number) => Promise<boolean>;
  requestTrust: () => Promise<boolean>;
  requestTrustWithToken: (_: string) => Promise<boolean>;
  call: DevframeRpcClientCall;
  callEvent: DevframeRpcClientCallEvent;
  callOptional: DevframeRpcClientCallOptional;
  client: DevframeClientRpcHost;
  sharedState: RpcSharedStateHost;
  streaming: RpcStreamingClientHost;
  cacheManager: RpcCacheManager;
}
export interface DevframeRpcClientMode {
  readonly isTrusted: boolean;
  ensureTrusted: DevframeRpcClient['ensureTrusted'];
  requestTrust: DevframeRpcClient['requestTrust'];
  requestTrustWithToken: DevframeRpcClient['requestTrustWithToken'];
  call: DevframeRpcClient['call'];
  callEvent: DevframeRpcClient['callEvent'];
  callOptional: DevframeRpcClient['callOptional'];
}
export interface DevframeRpcClientOptions {
  connectionMeta?: ConnectionMeta;
  baseURL?: string | string[];
  authToken?: string;
  wsOptions?: Partial<WsRpcChannelOptions>;
  rpcOptions?: Partial<BirpcOptions<DevframeRpcServerFunctions, DevframeRpcClientFunctions, boolean>>;
  cacheOptions?: boolean | Partial<RpcCacheOptions>;
}
export interface DevframeRpcContext {
  readonly rpc: DevframeRpcClient;
}
export interface RpcClientEvents {
  'rpc:is-trusted:updated': (_: boolean) => void;
}
export interface RpcStreamingClientHost {
  subscribe: <T = unknown>(_: string, _: string, _?: StreamingSubscribeOptions) => StreamReader<T>;
  upload: <T = unknown>(_: string, _: string) => StreamSink<T>;
}
export interface StreamingSubscribeOptions {
  highWaterMark?: number;
}
// #endregion

// #region Types
export type DevframeClientRpcHost = RpcFunctionsCollector<DevframeRpcClientFunctions, DevframeRpcContext>;
export type DevframeRpcClientCall = BirpcReturn<DevframeRpcServerFunctions, DevframeRpcClientFunctions>['$call'];
export type DevframeRpcClientCallEvent = BirpcReturn<DevframeRpcServerFunctions, DevframeRpcClientFunctions>['$callEvent'];
export type DevframeRpcClientCallOptional = BirpcReturn<DevframeRpcServerFunctions, DevframeRpcClientFunctions>['$callOptional'];
// #endregion

// #region Functions
export declare function createRpcStreamingClientHost(_: DevframeRpcClient): RpcStreamingClientHost;
export declare function getDevframeRpcClient(_?: DevframeRpcClientOptions): Promise<DevframeRpcClient>;
// #endregion

// #region Variables
export declare const connectDevframe: typeof getDevframeRpcClient;
// #endregion