/**
 * Generated by tsnapi — public API snapshot of `devframe/constants`
 */
// #region Functions
export declare function isAnonymousRpcMethod(_: string): boolean;
// #endregion

// #region Variables
export declare const ANONYMOUS_RPC_PREFIX: string;
export declare const DEVFRAME_AUTH_TOKEN_QUERY_PARAM: string;
export declare const DEVFRAME_CONNECTION_KEY: string;
export declare const DEVFRAME_CONNECTION_META_FILENAME: string;
export declare const DEVFRAME_DOCK_IMPORTS_FILENAME: string;
export declare const DEVFRAME_EVENTS: {
  readonly bus: {
    readonly agentManifestChanged: "agent:manifest:changed";
    readonly agentToolRegistered: "agent:tool:registered";
    readonly agentToolUnregistered: "agent:tool:unregistered";
    readonly agentResourceRegistered: "agent:resource:registered";
    readonly agentResourceUnregistered: "agent:resource:unregistered";
    readonly agentResourceUpdated: "agent:resource:updated";
  };
  readonly client: {
    readonly isTrustedUpdated: "rpc:is-trusted:updated";
    readonly error: "rpc:error";
    readonly connectionStatus: "connection:status";
    readonly connectionError: "connection:error";
  };
  readonly broadcast: {
    readonly authRevoked: "devframe:auth:revoked";
    readonly clientStateUpdated: "devframe:rpc:client-state:updated";
    readonly clientStatePatch: "devframe:rpc:client-state:patch";
    readonly streamingChunk: "devframe:streaming:chunk";
    readonly streamingEnd: "devframe:streaming:end";
    readonly streamingUploadCancel: "devframe:streaming:upload-cancel";
  };
  readonly inPageChannel: {
    readonly panelStateUpdated: "devframe:in-page:panel-state:updated";
    readonly panelStatePatch: "devframe:in-page:panel-state:patch";
  };
  readonly postMessage: {
    readonly remoteAssetsError: "devframe:remote-assets-error";
    readonly inPageChannel: "devframe:in-page-channel";
  };
};
export declare const DEVFRAME_MCP_ROUTE: string;
export declare const DEVFRAME_OTP_URL_PARAM: string;
export declare const DEVFRAME_REMOTE_ASSETS_ERROR_MESSAGE_TYPE: string;
export declare const DEVFRAME_RPC_DUMP_DIRNAME: string;
export declare const DEVFRAME_RPC_DUMP_MANIFEST_FILENAME: string;
export declare const DEVFRAME_SERVICES_STATE_KEY: string;
export declare const DEVFRAME_SSE_ROUTE: string;
export declare const DEVFRAME_SSE_SESSION_HEADER: string;
export declare const DEVFRAME_VIEWER_ORIGIN_QUERY_PARAM: string;
export declare const DEVFRAME_VIEWER_ORIGIN_TOKEN_QUERY_PARAM: string;
export declare const DEVFRAME_WS_ROUTE: string;
export declare const REMOTE_CONNECTION_KEY: string;
// #endregion