/**
 * Generated by tsnapi — public API snapshot of `devframe/in-page-channel`
 */
// #region Interfaces
export interface ConnectPanelChannelOptions<Protocol extends InPageChannelProtocol = InPageChannelProtocol> extends InPageChannelCommonOptions {
  functions: ConnectPanelChannelOptionsFunctions<Protocol>;
  window?: Window | false;
  targets?: Window[];
  transport?: MessagePort;
  instanceId?: string;
  helloIntervalMs?: number;
  eventBufferLimit?: number;
}
export interface CreatePageScriptChannelOptions<Protocol extends InPageChannelProtocol = InPageChannelProtocol> extends InPageChannelCommonOptions {
  functions: CreatePageScriptChannelOptionsFunctions<Protocol>;
  window?: Window | false;
}
export interface InPageChannelProtocol {
  pageScript?: Record<string, (...args: any[]) => any>;
  panel?: Record<string, (...args: any[]) => any>;
  sharedStates?: Record<string, object>;
}
export interface PageScriptChannel<P extends InPageChannelProtocol> {
  readonly name: string;
  readonly instanceId: string;
  readonly panels: readonly PanelPeer<P>[];
  readonly events: Pick<EventEmitter<PageScriptChannelEvents<P>>, 'on' | 'once'>;
  emit: <K extends keyof PanelFunctions<P> & string>(_: K, ..._: FnArgs<PanelFunctions<P>[K]>) => void;
  callEvent: <K extends keyof PanelFunctions<P> & string>(_: K, ..._: FnArgs<PanelFunctions<P>[K]>) => void;
  on: <K extends keyof PageScriptFunctions<P> & string>(_: K, _: (..._: FnArgs<PageScriptFunctions<P>[K]>) => void) => () => void;
  readonly sharedState: InPageSharedStateHost<P>;
  addPanelPort: (_: MessagePort) => PanelPeer<P>;
  close: () => void;
}
export interface PanelChannel<P extends InPageChannelProtocol> {
  readonly name: string;
  readonly status: InPageChannelStatus;
  readonly pageScript: {
    instanceId: string;
  } | undefined;
  readonly events: Pick<EventEmitter<PanelChannelEvents>, 'on' | 'once'>;
  whenConnected: (_?: number) => Promise<void>;
  call: <K extends keyof PageScriptFunctions<P> & string>(_: K, ..._: FnArgs<PageScriptFunctions<P>[K]>) => Promise<FnReturn<PageScriptFunctions<P>[K]>>;
  emit: <K extends keyof PageScriptFunctions<P> & string>(_: K, ..._: FnArgs<PageScriptFunctions<P>[K]>) => void;
  callEvent: <K extends keyof PageScriptFunctions<P> & string>(_: K, ..._: FnArgs<PageScriptFunctions<P>[K]>) => void;
  on: <K extends keyof PanelFunctions<P> & string>(_: K, _: (..._: FnArgs<PanelFunctions<P>[K]>) => void) => () => void;
  readonly sharedState: InPageSharedStateHost<P>;
  close: () => void;
}
export interface PanelPeer<P extends InPageChannelProtocol> {
  readonly id: string;
  call: <K extends keyof PanelFunctions<P> & string>(_: K, ..._: FnArgs<PanelFunctions<P>[K]>) => Promise<FnReturn<PanelFunctions<P>[K]>>;
  close: () => void;
}
// #endregion

// #region Types
export type InPageChannelErrorCode = 'timeout' |
'closed' |
'not-serializable' |
'not-cloneable' |
'invalid-args' |
'state-uninitialized';
export type InPageChannelStatus = 'connecting' | 'connected' | 'closed';
export type InPageFunctionDefinition<NAME extends string, TYPE extends InPageFunctionType = 'query', ARGS extends any[] = [], RETURN = void, AS extends RpcArgsSchema | undefined = undefined, RS extends RpcReturnSchema | undefined = undefined> = [AS, RS] extends [undefined, undefined] ? ({
  name: NAME;
  type?: TYPE;
  args?: AS;
  returns?: RS;
  jsonSerializable?: boolean;
} & (TYPE extends 'event' ? {
  handler?: (...args: ARGS) => RETURN;
} : {
  handler: (...args: ARGS) => RETURN;
})) : ({
  name: NAME;
  type?: TYPE;
  args: AS;
  returns: RS;
  jsonSerializable?: boolean;
} & (TYPE extends 'event' ? {
  handler?: (...args: InferArgsType<AS>) => Thenable<InferReturnType<RS>>;
} : {
  handler: (...args: InferArgsType<AS>) => Thenable<InferReturnType<RS>>;
}));
// #endregion

// #region Classes
export declare class InPageChannelError extends Error {
  readonly code: InPageChannelErrorCode;
  name: string;
  constructor(_: InPageChannelErrorCode, _: string, _?: {
    cause?: unknown;
  });
}
// #endregion

// #region Functions
export declare function connectPanelChannel<P extends InPageChannelProtocol>(_: ConnectPanelChannelOptions<P>): PanelChannel<P>;
export declare function createPageScriptChannel<P extends InPageChannelProtocol>(_: CreatePageScriptChannelOptions<P>): PageScriptChannel<P>;
export declare function defineChannelFunction<NAME extends string, TYPE extends InPageFunctionType, ARGS extends any[] = [], RETURN = void, const AS extends RpcArgsSchema | undefined = undefined, const RS extends RpcReturnSchema | undefined = undefined>(_: InPageFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS>): InPageFunctionDefinition<NAME, TYPE, ARGS, RETURN, AS, RS>;
// #endregion

// #region Referenced (internal)
type ConnectPanelChannelOptionsFunctions<P extends InPageChannelProtocol> = { [NAME in keyof PanelFunctions<P> & string]: InPageFunctionOption<PanelFunctions<P>[NAME]>; };
type CreatePageScriptChannelOptionsFunctions<P extends InPageChannelProtocol> = { [NAME in keyof PageScriptFunctions<P> & string]: InPageFunctionOption<PageScriptFunctions<P>[NAME]>; };
type FnArgs<F> = F extends ((...args: infer A) => any) ? A : never;
type FnReturn<F> = F extends ((...args: any[]) => infer R) ? Awaited<R> : never;
interface InPageChannelCommonOptions {
  name: string;
  allowedOrigins?: string[];
  callTimeoutMs?: number;
  heartbeat?: {
    intervalMs?: number;
    timeoutMs?: number;
  } | false;
  serialize?: (_: unknown) => unknown;
  deserialize?: (_: unknown) => unknown;
}
type InPageFunctionType = 'action' | 'event' | 'query';
interface InPageSharedStateHost<P extends InPageChannelProtocol> {
  get: <K extends keyof SharedStates<P> & string>(_: K, _?: {
    initialValue?: SharedStates<P>[K];
  }) => Promise<SharedState<SharedStates<P>[K]>>;
}
interface PageScriptChannelEvents<P extends InPageChannelProtocol> {
  'panel:connected': (_: PanelPeer<P>) => void;
  'panel:disconnected': (_: PanelPeer<P>) => void;
}
type PageScriptFunctions<P extends InPageChannelProtocol> = SideFunctions<NonNullable<P['pageScript']>>;
interface PanelChannelEvents {
  'status:updated': (_: InPageChannelStatus) => void;
}
type PanelFunctions<P extends InPageChannelProtocol> = SideFunctions<NonNullable<P['panel']>>;
// #endregion