/**
 * Generated by tsnapi — public API snapshot of `devframe/initiate`
 */
// #region Interfaces
export interface DevframeInstance {
  base: string;
  handler: (_: Request) => Promise<Response>;
  nodeMiddleware: (_: IncomingMessage, _: ServerResponse, _?: (_?: unknown) => void) => void;
  attach: (_: Server) => () => void;
  handleUpgrade: (_: IncomingMessage, _: Duplex, _: Buffer) => void;
  ready: Promise<void>;
  context: Promise<DevframeNodeContext>;
  connectionMeta: () => ConnectionMeta;
  close: () => Promise<void>;
}
export interface DevframeInstanceInternals {
  readonly started?: StartedServer;
  readonly authHandler?: DevframeAuthHandler;
}
export interface InitDevframeOptions {
  base: string;
  distDir?: StaticAssetsSource | false;
  server?: Server;
  ws?: DevframeWsOptions | false;
  sse?: boolean | DevframeSseOptions;
  host?: string;
  auth?: boolean | DevframeAuthHandler;
  mcp?: McpSetting;
  origin?: string | (() => string);
  register?: boolean | Partial<DevframeInstanceRecord>;
  flags?: Record<string, unknown>;
  allowedOrigins?: readonly string[] | WsOriginRegistry | false;
  app?: H3;
  getStorageDir?: (_: DevframeStorageScope) => string;
  destroyUnmatchedUpgrades?: boolean;
  onPeerConnect?: (_: DevframeRpcConnection, _: DevframeNodeRpcSession) => void;
  onPeerDisconnect?: (_: DevframeRpcConnection, _: DevframeNodeRpcSessionMeta) => void;
}
// #endregion

// #region Functions
export declare function getInstanceInternals(_: object): DevframeInstanceInternals;
export declare function initDevframe(_: DevframeDefinition, _: InitDevframeOptions): DevframeInstance;
// #endregion