/**
 * Generated by tsnapi — public API snapshot of `devframe/internal`
 */
// #region Interfaces
export interface DevframeInstanceRecord {
  pid: number;
  port: number;
  origin: string;
  basePath: string;
  id: string;
  name?: string;
  rootDir: string;
  mcp: {
    path: string;
  } | null;
  startedAt: number;
}
export interface DevframeInstanceRegistration {
  readonly file: string;
  unregister: () => void;
}
// #endregion

// #region Types
export type AgentArgsFallback = 'wrap' | 'drop';
// #endregion

// #region Classes
export declare class DevframeAgentHost implements DevframeAgentHost$1 {
  readonly context: DevframeNodeContext;
  readonly events: EventEmitter<DevframeAgentHostEvents>;
  private readonly tools;
  private readonly resources;
  private readonly providers;
  private _rpcUnsubscribe;
  constructor(_: DevframeNodeContext);
  registerTool(_: AgentToolInput): AgentHandle;
  unregisterTool(_: string): boolean;
  registerToolProvider(_: AgentToolProvider): AgentToolProviderHandle;
  registerResource(_: AgentResourceInput): AgentHandle;
  unregisterResource(_: string): boolean;
  list(): AgentManifest;
  getTool(_: string): AgentTool | undefined;
  getResource(_: string): AgentResource | undefined;
  invoke(_: string, _: unknown): Promise<unknown>;
  read(_: string): Promise<AgentResourceContent>;
  _dispose(): void;
  private _validateToolId;
  private _projectTool;
  private _collectProviderTools;
  private _collectRpcTools;
  private _findRpcDefinition;
}
// #endregion

// #region Functions
export declare function coerceAgentPositionalArgs(_: unknown, _: readonly unknown[] | undefined, _?: AgentArgsFallback): unknown[];
export declare function isObject(_: unknown): value is Record<string, any>;
export declare function listLiveDevframeInstances(_?: {
  instancesDir?: string;
  timeoutMs?: number;
}): Promise<{
  live: DevframeInstanceRecord[];
  pruned: DevframeInstanceRecord[];
}>;
export declare function normalizeHttpServerUrl(_: string, _: number | string): string;
export declare function registerDevframeInstance(_: DevframeInstanceRecord, _?: {
  instancesDir?: string;
}): DevframeInstanceRegistration;
// #endregion

// #region Other
export { ContextRpcServer }
export { createContextRpcServer }
export { CreateContextRpcServerOptions }
// #endregion