/**
 * Generated by tsnapi — public API snapshot of `devframe/internal`
 */
// #region Interfaces
export interface CreateH3DevframeHostOptions {
  app?: unknown;
  origin: string | (() => string);
  mount?: (_: string, _: string) => void | Promise<void>;
  appName: string;
  workspaceRoot?: string;
}
export interface CreateInstanceShellOptions<TContext extends DevframeNodeContext> {
  base: string;
  app?: H3;
  origin?: string | (() => string);
  auth?: boolean | DevframeAuthHandler;
  server?: Server;
  ws?: DevframeWsOptions;
  host?: string;
  allowedOrigins?: readonly string[] | WsOriginRegistry | false;
  destroyUnmatchedUpgrades?: boolean;
  onPeerConnect?: (_: Peer, _: DevframeNodeRpcSession) => void;
  onPeerDisconnect?: (_: Peer, _: DevframeNodeRpcSessionMeta) => void;
  absoluteWsPath?: boolean;
  resolveSidecarPort?: (_: string) => Promise<number>;
  init: (_: InstanceShellApi) => Promise<InstanceShellInit<TContext>>;
  mount?: (_: TContext, _: ConnectionMeta, _: InstanceShellApi) => void | Promise<void>;
  onMetaUnavailable: () => never;
}
export interface DevframeInstanceRecord {
  pid: number;
  port: number;
  origin: string;
  basePath: string;
  id: string;
  name?: string;
  rootDir: string;
  mcp: {
    path: string;
  } | null;
  startedAt: number;
}
export interface DevframeInstanceRegistration {
  readonly file: string;
  unregister: () => void;
}
export interface InstanceShell<TContext extends DevframeNodeContext> {
  base: string;
  handler: (_: Request) => Promise<Response>;
  nodeMiddleware: (_: IncomingMessage, _: ServerResponse, _?: (_?: unknown) => void) => void;
  ready: Promise<void>;
  context: Promise<TContext>;
  connectionMeta: () => ConnectionMeta;
  handleUpgrade: (_: IncomingMessage, _: Duplex, _: Buffer) => void;
  attach: (_: Server) => () => void;
  close: () => Promise<void>;
  internals: InstanceShellInternals;
}
export interface InstanceShellApi {
  base: string;
  app: H3;
  origin: () => string | undefined;
  connectionMeta: () => ConnectionMeta | undefined;
}
export interface InstanceShellInit<TContext extends DevframeNodeContext> {
  context: TContext;
  mcp?: ConnectionMeta['mcp'];
  dispose?: () => Promise<void>;
}
export interface InstanceShellInternals {
  readonly started?: StartedServer;
  readonly authHandler?: DevframeAuthHandler;
}
// #endregion

// #region Types
export type AgentArgsFallback = 'wrap' | 'drop';
export type InstanceWsTier = 'sidecar' | 'server' | 'external' | 'unbound';
// #endregion

// #region Classes
export declare class DevframeAgentHost implements DevframeAgentHost$1 {
  readonly context: DevframeNodeContext;
  readonly events: EventEmitter<DevframeAgentHostEvents>;
  private readonly tools;
  private readonly resources;
  private readonly providers;
  private _rpcUnsubscribe;
  constructor(_: DevframeNodeContext);
  registerTool(_: AgentToolInput): AgentHandle;
  unregisterTool(_: string): boolean;
  registerToolProvider(_: AgentToolProvider): AgentToolProviderHandle;
  registerResource(_: AgentResourceInput): AgentHandle;
  unregisterResource(_: string): boolean;
  list(): AgentManifest;
  getTool(_: string): AgentTool | undefined;
  getResource(_: string): AgentResource | undefined;
  invoke(_: string, _: unknown): Promise<unknown>;
  read(_: string): Promise<AgentResourceContent>;
  _dispose(): void;
  private _validateToolId;
  private _projectTool;
  private _collectProviderTools;
  private _collectRpcTools;
  private _findRpcDefinition;
}
// #endregion

// #region Functions
export declare function coerceAgentPositionalArgs(_: unknown, _: readonly unknown[] | undefined, _?: AgentArgsFallback): unknown[];
export declare function createH3DevframeHost(_: CreateH3DevframeHostOptions): DevframeHost;
export declare function createInstanceShell<TContext extends DevframeNodeContext>(_: CreateInstanceShellOptions<TContext>): InstanceShell<TContext>;
export declare function listLiveDevframeInstances(_?: {
  instancesDir?: string;
  timeoutMs?: number;
}): Promise<{
  live: DevframeInstanceRecord[];
  pruned: DevframeInstanceRecord[];
}>;
export declare function normalizeHttpServerUrl(_: string, _: number | string): string;
export declare function registerDevframeInstance(_: DevframeInstanceRecord, _?: {
  instancesDir?: string;
}): DevframeInstanceRegistration;
export declare function samePath(_: string, _: string): boolean;
// #endregion

// #region Other
export { ContextRpcServer }
export { createContextRpcServer }
export { CreateContextRpcServerOptions }
export { StartedServer }
export { startHttpAndWs }
export { StartHttpAndWsOptions }
// #endregion