/**
 * Generated by tsnapi — public API snapshot of `devframe/node`
 */
// #region Interfaces
export interface CreateHostContextOptions {
  cwd: string;
  workspaceRoot?: string;
  mode: 'dev' | 'build';
  host: DevframeHost;
  builtinRpcDeclarations?: readonly RpcFunctionDefinitionAny[];
}
export interface CreateStorageOptions<T extends object> {
  filepath: string;
  initialValue: T;
  mergeInitialValue?: false | ((_: T, _: T) => T);
  debounce?: number;
}
// #endregion

// #region Functions
export declare function createHostContext(_: CreateHostContextOptions): Promise<DevframeNodeContext>;
export declare function createStorage<T extends object>(_: CreateStorageOptions<T>): SharedState<T>;
export declare function installDefinitionServices(_: DevframeNodeContext, _: DevframeDefinition): void;
// #endregion

// #region Other
export { RpcFunctionsHost }
// #endregion